<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Log;

class MovieCategorySubsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      // Example sub-category groups with their respective category names
      $subCategoryGroups = [
          'Action' => [
              ['name' => 'Superhero', 'description' => 'Films featuring characters with superhuman abilities or heroic qualities, often based on comic books.'],
              ['name' => 'Martial Arts', 'description' => 'Focuses on hand-to-hand combat and martial arts techniques, showcasing skilled fighters and action sequences.'],
              ['name' => 'Adventure', 'description' => 'Centers around exciting and often risky journeys or expeditions, frequently in exotic locations.'],
              ['name' => 'Spy', 'description' => 'Revolve around espionage and intelligence, featuring spies, secret agents, and undercover operations.'],
              ['name' => 'Heist', 'description' => 'Focuses on the planning and execution of a theft or burglary, often involving intricate plots and twists.'],
              ['name' => 'War', 'description' => 'Depicts military conflicts, battles, and the life of soldiers, often set in historical or contemporary war settings.'],
              ['name' => 'Disaster', 'description' => 'Centers on catastrophic events like natural disasters, accidents, or apocalyptic scenarios.'],
              ['name' => 'Car Chase', 'description' => 'Features high-speed car chases, often with elaborate stunts and intense action sequences.'],
              ['name' => 'Science Fiction Action', 'description' => 'Blends action with sci-fi elements, including futuristic technology, space exploration, and extraterrestrial beings.'],
              ['name' => 'Fantasy Action', 'description' => 'Incorporates action within a fantasy setting, featuring magical elements, mythical creatures, and supernatural events.'],
              ['name' => 'Crime Action', 'description' => 'Combines action with crime themes, focusing on criminals, gangsters, or law enforcement chases.'],
              ['name' => 'Western Action', 'description' => 'Action films set in the American frontier, typically featuring cowboys, outlaws, and shootouts.'],
              ['name' => 'Thriller Action', 'description' => 'Merges action with suspenseful and thrilling elements, often involving a pursuit or a race against time.'],
              ['name' => 'Super Spy', 'description' => 'Centers on highly skilled and equipped secret agents embarking on international espionage missions.'],
              ['name' => 'Military', 'description' => 'Showcases military operations, tactics, and warfare, often with a focus on action-packed battle scenes.'],
          ],
          'Adventure' => [
              ['name' => 'Action-Adventure', 'description' => 'Combines elements of action with adventure, featuring thrilling sequences, daring exploits, and often a quest or journey.'],
              ['name' => 'Fantasy Adventure', 'description' => 'Involves fantastical elements and mythical settings, often including quests for magical objects or encounters with mythical creatures.'],
              ['name' => 'Survival Adventure', 'description' => 'Centers on characters surviving in harsh or dangerous environments, often featuring wilderness survival or disaster scenarios.'],
              ['name' => 'Historical Adventure', 'description' => 'Set in a historical context, often involving journeys or quests during significant historical periods or events.'],
              ['name' => 'Space Adventure', 'description' => 'Focuses on adventures in outer space, often involving space exploration, interstellar travel, and encounters with alien worlds.'],
              ['name' => 'Sea Adventure', 'description' => 'Set on or around the sea, involving maritime journeys, naval battles, or exploration of uncharted waters.'],
              ['name' => 'Jungle Adventure', 'description' => 'Takes place in jungle environments, often featuring exploration, treasure hunts, and encounters with wild animals or lost civilizations.'],
              ['name' => 'Treasure Hunt Adventure', 'description' => 'Centers around the search for hidden treasure or lost artifacts, often involving puzzles, clues, and ancient mysteries.'],
              ['name' => 'Expedition Adventure', 'description' => 'Involves expeditions or explorations, often in search of discoveries or to reach unexplored territories.'],
              ['name' => 'Sci-Fi Adventure', 'description' => 'Combines science fiction elements with adventure, often involving futuristic settings, advanced technology, and alien encounters.'],
              ['name' => 'Urban Adventure', 'description' => 'Adventure set in a city or urban environment, often involving navigating urban landscapes and overcoming metropolitan challenges.'],
              ['name' => 'Road Trip Adventure', 'description' => 'Focuses on adventures experienced during a road trip, often involving travel across different landscapes and self-discovery.'],
              ['name' => 'Pirate Adventure', 'description' => 'Set in the world of pirates, often involving sea voyages, treasure hunts, and battles on the high seas.'],
              ['name' => 'Desert Adventure', 'description' => 'Set in desert environments, often involving exploration, survival, and uncovering secrets hidden in the desert.'],
              ['name' => 'Mountain Adventure', 'description' => 'Centers around adventures in mountainous regions, often involving climbing, exploration, or overcoming natural challenges.'],
              ['name' => 'Time Travel Adventure', 'description' => 'Involves traveling through time, experiencing different historical periods or future settings as part of the adventure.'],
              ['name' => 'Quest Adventure', 'description' => 'Centers on a quest or mission, often involving a journey to accomplish a specific goal or to find a significant object.'],
              ['name' => 'Mythological Adventure', 'description' => 'Involves mythological elements, often drawing on ancient myths, legends, and folklore as the basis for the adventure.'],
              ['name' => 'Children’s Adventure', 'description' => 'Adventure films geared towards children, often featuring young protagonists and family-friendly themes.'],
              ['name' => 'Mystery Adventure', 'description' => 'Combines elements of mystery with adventure, often involving the solving of riddles, mysteries, or uncovering hidden truths.'],
          ],
          'Animated' => [
              ['name' => 'Children\'s Animation', 'description' => 'Animation tailored for a younger audience, featuring child-friendly themes and characters.'],
              ['name' => 'Anime', 'description' => 'Japanese animation known for its diverse art styles, themes, and genres, appealing to a wide range of audiences.'],
              ['name' => 'Computer Animation', 'description' => 'Uses computer-generated imagery (CGI) for creating animated scenes, known for its realistic textures and details.'],
              ['name' => 'Stop Motion', 'description' => 'Animation technique where objects are physically manipulated in small increments between photographed frames, creating the illusion of movement.'],
              ['name' => 'Adult Animation', 'description' => 'Animation that is aimed at adults, often including mature themes, humor, and complex storytelling.'],
              ['name' => 'Cartoon', 'description' => 'Traditional form of animation known for its exaggerated features and characters, primarily aimed at children but with some appeal to adults.'],
              ['name' => 'Clay Animation', 'description' => 'A form of stop motion using characters made of clay or a similar malleable material.'],
              ['name' => 'Fantasy Animation', 'description' => 'Animation set in fantastical worlds with magic, mythical creatures, and imaginative scenarios.'],
              ['name' => 'Science Fiction Animation', 'description' => 'Explores futuristic concepts, scientific advancements, space travel, and extraterrestrial life.'],
              ['name' => 'Action Animation', 'description' => 'Focused on fast-paced and dynamic sequences, often involving conflicts, fights, and chases.'],
              ['name' => 'Adventure Animation', 'description' => 'Centers around journeys and explorations, often in new or exciting settings.'],
              ['name' => 'Drama Animation', 'description' => 'Focuses on character development and emotional narratives, addressing serious themes.'],
              ['name' => 'Educational Animation', 'description' => 'Designed to educate and inform, often used in schools and learning programs.'],
              ['name' => 'Experimental Animation', 'description' => 'Pushes the boundaries of traditional animation techniques and storytelling, often avant-garde and artistic.'],
              ['name' => 'Musical Animation', 'description' => 'Combines animation with musical elements, featuring songs and music-driven narratives.'],
          ],
          'Biopics' => [
              ['name' => 'Historical Figures', 'description' => 'Biopics focusing on significant individuals from history, including kings, queens, and historical leaders.'],
              ['name' => 'Musicians and Composers', 'description' => 'Centers on the lives and careers of famous musicians, singers, and composers, exploring their art and personal journeys.'],
              ['name' => 'Political Figures', 'description' => 'Biographical films about politicians, statesmen, and political activists, often exploring their political careers and impacts.'],
              ['name' => 'Artists and Writers', 'description' => 'Biopics that delve into the lives of painters, sculptors, writers, and poets, focusing on their creative process and personal stories.'],
              ['name' => 'Sports Figures', 'description' => 'Tells the stories of famous sports personalities, their careers, challenges, and achievements in the sports world.'],
              ['name' => 'Scientists and Innovators', 'description' => 'Focuses on the lives of notable scientists, inventors, and innovators, highlighting their discoveries and contributions to their fields.'],
              ['name' => 'Entertainment Industry', 'description' => 'Biopics of actors, filmmakers, and entertainers, exploring their careers in the entertainment industry and personal lives.'],
              ['name' => 'Activists and Humanitarians', 'description' => 'Portrays the lives of social activists, humanitarians, and individuals who have made significant contributions to social causes.'],
              ['name' => 'Explorers and Adventurers', 'description' => 'Centers on the lives of explorers, adventurers, and travelers, documenting their explorations and experiences.'],
              ['name' => 'Cultural Icons', 'description' => 'Focuses on influential personalities who have become icons in popular culture, including their rise to fame and cultural impact.'],
              ['name' => 'Military Leaders', 'description' => 'Biopics about military figures, focusing on their leadership, battles, and military strategies.'],
              ['name' => 'Religious Figures', 'description' => 'Depicts the lives of significant religious leaders and figures, exploring their teachings, philosophies, and impacts.'],
              ['name' => 'Royalty', 'description' => 'Focuses on members of royal families, exploring their lives, reigns, and the political dynamics of their times.'],
              ['name' => 'Underground Figures', 'description' => 'Centers on the lives of individuals from the underworld, such as gangsters, outlaws, and figures from the criminal world.'],
              ['name' => 'Real-Life Heroes', 'description' => 'Tells the stories of real-life heroes who have demonstrated extraordinary courage, resilience, or altruism.'],
          ],
          'Comedy' => [
              ['name' => 'Romantic Comedy', 'description' => 'Comedies that focus on romantic relationships, typically featuring humorous plotlines centered around romantic pursuits and relationships.'],
              ['name' => 'Slapstick', 'description' => 'Characterized by physical humor, slapstick comedies often involve exaggerated, boisterous actions and visual gags.'],
              ['name' => 'Satire', 'description' => 'Uses humor, irony, and exaggeration to criticize or ridicule societal norms, politics, and other topical issues.'],
              ['name' => 'Screwball Comedy', 'description' => 'A genre of comedy film that became popular during the Great Depression, characterized by fast-paced repartee, farcical situations, escapist themes, and plot lines involving courtship and marriage.'],
              ['name' => 'Dark Comedy', 'description' => 'Also known as black comedy, this sub-genre combines humor with more serious, often taboo or grim subjects like death, war, and crime.'],
              ['name' => 'Parody', 'description' => 'Imitates the style of a particular genre, work, or author for comedic effect, often by exaggerating and humorously criticizing the original work.'],
              ['name' => 'Spoof', 'description' => 'Similar to parodies, spoofs are light-hearted attempts to mimic and make fun of specific genres or works.'],
              ['name' => 'Mockumentary', 'description' => 'Presents fictional events in the form of a documentary, often to satirize the subject or documentary method itself.'],
              ['name' => 'Sitcom', 'description' => 'Short for "situational comedy," these films often revolve around a fixed set of characters in a relatively consistent setting.'],
              ['name' => 'Stand-up Comedy', 'description' => 'Features a comedian performing in front of a live audience, delivering humorous monologues, jokes, and anecdotes.'],
              ['name' => 'Musical Comedy', 'description' => 'Combines comedic elements with musical performances, often featuring characters who express themselves through song and dance.'],
              ['name' => 'Family Comedy', 'description' => 'Suitable for a family audience, these comedies often involve family dynamics and are appropriate for all ages.'],
              ['name' => 'Teen Comedy', 'description' => 'Targets a teenage audience and typically revolves around themes like high school life, coming of age, and first love.'],
              ['name' => 'Buddy Comedy', 'description' => 'Centers on the relationship between two or more friends, often featuring misadventures and comical situations arising from their friendship.'],
              ['name' => 'Fish out of Water', 'description' => 'Characters find themselves in an unfamiliar, unusual, or bizarre situation, leading to comedic misadventures.'],
              ['name' => 'Road Comedy', 'description' => 'Focuses on a journey or road trip, with humor derived from the adventures and mishaps along the way.'],
              ['name' => 'Office Comedy', 'description' => 'Set in a workplace environment, often highlighting humorous interactions among employees and office politics.'],
              ['name' => 'Political Comedy', 'description' => 'Revolve around political scenarios, campaigns, or figures, often satirizing political processes and figures.'],
              ['name' => 'Sports Comedy', 'description' => 'Uses a sports setting and sports-related themes to create humor, often involving underdog teams or athletes.'],
              ['name' => 'Holiday Comedy', 'description' => 'Centered around a specific holiday, using the backdrop of the holiday season to create comedic situations.'],
          ],
          'Crime' => [
              ['name' => 'Detective', 'description' => 'Centers around investigators or detectives solving mysteries and crimes, often featuring complex plots and intellectual twists.'],
              ['name' => 'Gangster', 'description' => 'Focuses on the lives of criminals involved in organized crime, such as mobsters, gang leaders, and the mafia.'],
              ['name' => 'Heist', 'description' => 'Revolves around the planning and execution of a theft or robbery, often with intricate plots and suspenseful sequences.'],
              ['name' => 'Noir', 'description' => 'Characterized by a dark, cynical tone, focusing on crime, moral ambiguity, and complex characters, often in a stylish, shadowy setting.'],
              ['name' => 'Police Procedural', 'description' => 'Follows law enforcement officers and detectives as they solve crimes, emphasizing procedural and investigative techniques.'],
              ['name' => 'Legal Drama', 'description' => 'Centers on legal and judicial processes, often involving lawyers, judges, and the complexities of legal cases.'],
              ['name' => 'Crime Thriller', 'description' => 'Combines elements of crime and thriller genres, with suspenseful, high-stakes plots involving criminal activities.'],
              ['name' => 'True Crime', 'description' => 'Based on real-life criminal cases and events, often delving into the details and motivations behind the crimes.'],
              ['name' => 'Mystery', 'description' => 'Focuses on the unfolding of a mystery, often involving a crime, where characters seek to uncover secrets or solve puzzles.'],
              ['name' => 'Capo', 'description' => 'Focuses on the rise and fall of a crime boss, exploring the power dynamics within criminal organizations.'],
              ['name' => 'Undercover', 'description' => 'Revolves around characters going undercover, often within criminal organizations, leading to tension and moral dilemmas.'],
              ['name' => 'Caper', 'description' => 'A lighthearted or humorous crime film, often featuring a group of characters attempting a daring or elaborate theft.'],
              ['name' => 'White-Collar Crime', 'description' => 'Deals with crimes committed by business or government professionals, often involving fraud, embezzlement, or corruption.'],
              ['name' => 'Cybercrime', 'description' => 'Focuses on crimes related to technology, such as hacking, online fraud, and other computer-related criminal activities.'],
              ['name' => 'Vigilante', 'description' => 'Centers on individuals taking the law into their own hands, often to seek justice or revenge outside the legal system.'],
              ['name' => 'Organized Crime', 'description' => 'Revolves around criminal organizations and their activities, including drug trafficking, smuggling, and racketeering.'],
              ['name' => 'Psychological Crime', 'description' => 'Emphasizes the psychological states and motivations of criminals or victims, often exploring themes of obsession and manipulation.'],
              ['name' => 'Juvenile Crime', 'description' => 'Focuses on young or teenage characters involved in criminal activities, often exploring themes of youth and delinquency.'],
              ['name' => 'Film Noir', 'description' => 'A style or genre of cinematic film marked by a mood of pessimism, fatalism, and menace.'],
              ['name' => 'Ethnic and Racial Crime', 'description' => 'Explores crime within specific ethnic or racial communities, often addressing social and cultural issues.'],
          ],
          'Cult Films' => [
              ['name' => 'Midnight Cult', 'description' => 'Films known for late-night showings, often featuring bizarre, surreal, or campy content, attracting a dedicated nocturnal audience.'],
              ['name' => 'Sci-Fi Cult', 'description' => 'Science fiction films that have gained a cult following for their imaginative and often unconventional approach to the genre.'],
              ['name' => 'Horror Cult', 'description' => 'Horror films with a dedicated fanbase, often celebrated for their unique, sometimes campy approach to scares and thrills.'],
              ['name' => 'Comedy Cult', 'description' => 'Comedy films that have attained cult status, often due to their quirky humor, satirical narratives, or eccentric characters.'],
              ['name' => 'Action Cult', 'description' => 'Action films revered for their over-the-top sequences, iconic heroes, or unique stylistic choices, gathering a dedicated following.'],
              ['name' => 'Fantasy Cult', 'description' => 'Fantasy films with a cult following, often beloved for their imaginative worlds, distinctive style, or mythical storytelling.'],
              ['name' => 'Drama Cult', 'description' => 'Dramatic films that have garnered a cult following, often due to their emotional depth, unconventional narratives, or cult status actors.'],
              ['name' => 'Thriller Cult', 'description' => 'Thriller films that have captured a dedicated audience, often due to their intense, unconventional, or suspenseful nature.'],
              ['name' => 'Romantic Cult', 'description' => 'Romantic films that have developed a cult following, often for their unconventional approach to romance or unique storytelling.'],
              ['name' => 'Indie Cult', 'description' => 'Independent films that have gained a cult following, often noted for their originality, artistic vision, or unconventional storytelling.'],
              ['name' => 'Animated Cult', 'description' => 'Animated films that have attracted a cult following, often due to their unique animation style, storytelling, or adult themes.'],
              ['name' => 'Musical Cult', 'description' => 'Musical films with a dedicated fanbase, often known for their memorable songs, unique storytelling, or theatrical flair.'],
              ['name' => 'Documentary Cult', 'description' => 'Documentaries that have gained cult status, often due to their subject matter, unconventional approach, or controversial nature.'],
              ['name' => 'Experimental Cult', 'description' => 'Films that push the boundaries of conventional cinema, often noted for their avant-garde style, innovative narrative, or artistic expression.'],
              ['name' => 'Foreign Language Cult', 'description' => 'Non-English language films that have garnered international cult followings, often due to their unique cultural perspective or cinematic style.'],
              ['name' => 'Psychedelic Cult', 'description' => 'Films known for their psychedelic imagery, trippy narratives, or representation of altered states of consciousness.'],
              ['name' => 'Camp Cult', 'description' => 'Films celebrated for their campy style, including over-the-top performances, kitschy aesthetics, or melodramatic elements.'],
              ['name' => 'LGBTQ+ Cult', 'description' => 'Films that have become cult favorites in the LGBTQ+ community, often for their representation, themes, or style.'],
              ['name' => 'Grindhouse Cult', 'description' => 'Films known for their low-budget production and exploitation-style content, often including horror, action, and other sensational genres.'],
              ['name' => 'Cult Classics', 'description' => 'Older films that have remained popular over time and developed a dedicated and passionate fanbase, often revered for their impact and influence.'],
          ],
          'Drama' => [
              ['name' => 'Romantic Drama', 'description' => 'Centers on romantic relationships, exploring emotional and moral conflicts through love stories.'],
              ['name' => 'Period Drama', 'description' => 'Set in a particular historical period, often focusing on the social and cultural conditions of that era.'],
              ['name' => 'Legal Drama', 'description' => 'Revolves around legal and judicial settings, often involving lawyers, court trials, and the intricacies of the legal system.'],
              ['name' => 'Family Drama', 'description' => 'Focuses on family relationships and dynamics, exploring issues within family units and interpersonal conflicts.'],
              ['name' => 'Crime Drama', 'description' => 'Combines elements of drama and crime, focusing on the psychological and moral complexities of crime and justice.'],
              ['name' => 'Political Drama', 'description' => 'Centers on political topics, including government, political processes, and the lives of political figures.'],
              ['name' => 'Social Drama', 'description' => 'Addresses societal issues and themes, such as poverty, gender, race, and social injustices.'],
              ['name' => 'War Drama', 'description' => 'Depicts the realities of war, focusing on the human experiences and emotional impacts of conflict.'],
              ['name' => 'Psychological Drama', 'description' => 'Explores the psychological states of characters, often delving into themes like mental health, identity, and human behavior.'],
              ['name' => 'Sports Drama', 'description' => 'Centers around sports and athletes, often exploring personal growth, competition, and perseverance.'],
              ['name' => 'Coming-of-Age Drama', 'description' => 'Focuses on the growth and personal development of a young protagonist, often from youth to adulthood.'],
              ['name' => 'Historical Drama', 'description' => 'Based on real historical events or figures, often blending factual and fictional elements to dramatize history.'],
              ['name' => 'Biographical Drama', 'description' => 'Tells the life stories of real people, ranging from historical figures to contemporary personalities.'],
              ['name' => 'Tragedy', 'description' => 'Characterized by serious themes and somber tones, often involving the downfall or suffering of the protagonist.'],
              ['name' => 'Melodrama', 'description' => 'Emphasizes heightened emotions and sensational plot developments, often dealing with sensational and romantic topics.'],
              ['name' => 'Courtroom Drama', 'description' => 'Set primarily in a courtroom, focusing on legal battles, moral dilemmas, and the pursuit of justice.'],
              ['name' => 'Medical Drama', 'description' => 'Set in medical environments like hospitals, following medical professionals and patient stories.'],
              ['name' => 'Fantasy Drama', 'description' => 'Combines elements of drama with fantasy, often including magical, mystical, or supernatural aspects.'],
              ['name' => 'Science Fiction Drama', 'description' => 'Integrates dramatic elements with science fiction, exploring futuristic, technological, or extraterrestrial themes.'],
              ['name' => 'Adventure Drama', 'description' => 'Combines dramatic narratives with adventure elements, often featuring journeys, explorations, and quests.'],
          ],
          'Documentary' => [
              ['name' => 'Nature Documentary', 'description' => 'Focuses on wildlife and natural environments, often showcasing ecosystems, wildlife behavior, and environmental issues.'],
              ['name' => 'Social Documentary', 'description' => 'Explores social issues, cultures, and human lifestyles, often highlighting societal challenges, injustices, and diverse ways of life.'],
              ['name' => 'Historical Documentary', 'description' => 'Centers on historical events, figures, and periods, often using archival footage, interviews, and reenactments to depict historical narratives.'],
              ['name' => 'Biographical Documentary', 'description' => 'Tells the life stories of individuals, whether famous personalities or ordinary people with extraordinary experiences.'],
              ['name' => 'Political Documentary', 'description' => 'Examines political issues, events, and figures, often exploring themes of power, governance, and policy-making.'],
              ['name' => 'Science Documentary', 'description' => 'Focuses on scientific topics, discoveries, and explorations, often explaining complex scientific concepts and innovations.'],
              ['name' => 'Music Documentary', 'description' => 'Explores the world of music, including genres, bands, musicians, and the cultural impact of music.'],
              ['name' => 'Art Documentary', 'description' => 'Centers on the visual arts, covering artists, art movements, galleries, and the creative process.'],
              ['name' => 'Sports Documentary', 'description' => 'Focuses on sports, athletes, and sporting events, often highlighting personal journeys, competitions, and the significance of sports.'],
              ['name' => 'Travel Documentary', 'description' => 'Explores different regions of the world, their landscapes, cultures, and customs, often emphasizing the experience of travel and discovery.'],
              ['name' => 'Environmental Documentary', 'description' => 'Examines environmental issues, conservation efforts, and the relationship between humans and the natural world.'],
              ['name' => 'Technology Documentary', 'description' => 'Focuses on technological advancements, digital culture, and the impact of technology on society and daily life.'],
              ['name' => 'Health and Wellness Documentary', 'description' => 'Explores health-related topics, medical research, wellness practices, and issues affecting the healthcare system.'],
              ['name' => 'True Crime Documentary', 'description' => 'Investigates real crime stories, often involving criminal cases, legal battles, and the pursuit of justice.'],
              ['name' => 'War Documentary', 'description' => 'Focuses on aspects of war, including conflicts, soldier experiences, and historical war narratives.'],
              ['name' => 'Cultural Documentary', 'description' => 'Explores cultural phenomena, traditions, and societal changes, often reflecting on human behavior and social dynamics.'],
              ['name' => 'Educational Documentary', 'description' => 'Aimed at providing educational content on various subjects, often used in academic or training contexts.'],
              ['name' => 'Experimental Documentary', 'description' => 'Utilizes experimental filmmaking techniques, often challenging traditional documentary forms and narratives.'],
              ['name' => 'Advocacy Documentary', 'description' => 'Created to advocate for a particular cause or viewpoint, often aiming to raise awareness or inspire action on specific issues.'],
              ['name' => 'Personal Documentary', 'description' => 'Centers on the filmmaker\'s personal stories, experiences, or perspectives, often blending the personal with the universal.']
          ],
          'Experimental' => [
              ['name' => 'Abstract Film', 'description' => 'Focuses on visual and auditory experiences without a narrative structure, often using shapes, colors, and textures for artistic expression.'],
              ['name' => 'Surrealist Film', 'description' => 'Emphasizes surreal and dreamlike sequences, often defying logical sequencing, standard narrative structures, and typical cinematic conventions.'],
              ['name' => 'Structural Film', 'description' => 'Characterized by an emphasis on the nature of the film medium itself and its materiality, often exploring the basic elements of time, space, and light.'],
              ['name' => 'Collage Film', 'description' => 'Involves the assembly of various disparate visual elements, often juxtaposing unrelated imagery to create new meanings or associations.'],
              ['name' => 'Conceptual Film', 'description' => 'Centers on a concept or idea, rather than traditional storytelling or character development, often challenging viewers’ perceptions.'],
              ['name' => 'Expanded Cinema', 'description' => 'Goes beyond traditional movie projection, incorporating multi-screen installations, audience interaction, and multimedia performances.'],
              ['name' => 'Participatory Film', 'description' => 'Involves the audience as active participants in the film\'s creation or experience, breaking the passive viewer paradigm.'],
              ['name' => 'Performance Art Film', 'description' => 'Combines elements of film with performance art, often capturing live performances or integrating performative elements.'],
              ['name' => 'Found Footage', 'description' => 'Employs existing footage from other films, newsreels, or archives, recontextualizing them to create new works.'],
              ['name' => 'Video Art', 'description' => 'Uses video technology for artistic expression, often shown in galleries or art installations rather than traditional cinema settings.'],
              ['name' => 'Interactive Film', 'description' => 'Allows viewer interaction, influencing the narrative flow or outcome of the film, often utilizing digital or online platforms.'],
              ['name' => 'Sound Art', 'description' => 'Emphasizes auditory experiences, using sound as the primary medium, often accompanied by visual elements that are secondary to the soundscapes.'],
              ['name' => 'Psychedelic Film', 'description' => 'Characterized by hallucinatory visuals, surreal imagery, and non-linear narratives, often aiming to replicate or enhance psychedelic experiences.'],
              ['name' => 'Digital Art Film', 'description' => 'Utilizes digital technology for artistic creation and expression, exploring the possibilities of digital media within the realm of film.'],
              ['name' => 'Installation Film', 'description' => 'Designed to be exhibited as part of an installation in an art gallery or similar space, focusing on the spatial experience of the viewer.'],
          ],
          'Family' => [
              ['name' => 'Animated Family', 'description' => 'Features animation in various forms (2D, 3D, stop-motion) and is typically suitable for children and family viewing.'],
              ['name' => 'Family Adventure', 'description' => 'Involves family-friendly adventures, often featuring journeys, discoveries, and a sense of wonder, suitable for all ages.'],
              ['name' => 'Family Comedy', 'description' => 'Centers on humorous situations and characters, appealing to a family audience with lighthearted and often heartwarming stories.'],
              ['name' => 'Family Drama', 'description' => 'Focuses on family dynamics and relationships, dealing with issues and challenges in a way that resonates with both kids and adults.'],
              ['name' => 'Fantasy Family', 'description' => 'Incorporates elements of fantasy, often including magical creatures, fantastical worlds, and adventurous quests suitable for a family audience.'],
              ['name' => 'Musical Family', 'description' => 'Features songs and musical numbers within a storyline that is suitable for children and family members of all ages.'],
              ['name' => 'Educational Family', 'description' => 'Designed to educate and entertain, often teaching moral lessons, educational content, or life skills in an engaging way.'],
              ['name' => 'Sports Family', 'description' => 'Focuses on sports themes, often involving underdog stories, sportsmanship, and overcoming challenges, suitable for family viewing.'],
              ['name' => 'Animal Family', 'description' => 'Centers on animal characters or the relationships between humans and animals, often highlighting themes of friendship and adventure.'],
              ['name' => 'Holiday Family', 'description' => 'Set around specific holidays, featuring themes and stories related to holiday celebrations, often emphasizing family and togetherness.'],
              ['name' => 'Science Fiction Family', 'description' => 'Introduces children to science fiction elements in a family-friendly setting, often with imaginative and educational plots.'],
              ['name' => 'Teen Family', 'description' => 'Aimed at teenagers and pre-teens, often dealing with coming-of-age themes, first experiences, and family relationships.'],
              ['name' => 'Superhero Family', 'description' => 'Features superheroes in a more family-oriented setting, often with less intense action and more focus on positive messages and fun.'],
              ['name' => 'Mystery Family', 'description' => 'Involves solving mysteries or engaging in adventures that are intriguing but still appropriate for a younger audience.'],
              ['name' => 'Fairy Tale Family', 'description' => 'Adaptations of fairy tales or original stories with elements of magic, princes and princesses, and moral lessons.'],
              ['name' => 'Historical Family', 'description' => 'Set in historical periods, often teaching about history in an entertaining way that is accessible to younger viewers.'],
              ['name' => 'Environmental Family', 'description' => 'Focuses on environmental themes and nature, often encouraging awareness and respect for the natural world among young audiences.'],
              ['name' => 'Fantastical Family', 'description' => 'Involves elements of the fantastic and extraordinary, sparking imagination and wonder in a family-friendly context.'],
              ['name' => 'Coming-of-Age Family', 'description' => 'Centers on the growth and development of young characters, often relating to themes of growing up, learning, and family support.'],
              ['name' => 'Cultural Family', 'description' => 'Explores different cultures and traditions, often offering educational insights into various lifestyles in a way that\'s accessible to families.'],
          ],
          'Fantasy' => [
              ['name' => 'High Fantasy', 'description' => 'Set in alternative, fictional worlds with its own rules and physical laws, often featuring epic quests and battles between good and evil.'],
              ['name' => 'Sword and Sorcery', 'description' => 'Centers on sword-wielding heroes and sorcerers, featuring elements of magic, mythical beasts, and ancient lore.'],
              ['name' => 'Urban Fantasy', 'description' => 'Blends fantasy elements into a modern, urban setting, often involving magical creatures or supernatural occurrences in contemporary cities.'],
              ['name' => 'Dark Fantasy', 'description' => 'Combines elements of fantasy with darker and sometimes horrifying themes, often creating a moody and gothic tone.'],
              ['name' => 'Mythic Fiction', 'description' => 'Incorporates traditional myths, legends, and folklore into its narrative, often reimagining or reinterpreting classic myths.'],
              ['name' => 'Fairy Tale', 'description' => 'Based on or inspired by traditional fairy tales, often featuring magical creatures, princesses, and enchanted realms.'],
              ['name' => 'Heroic Fantasy', 'description' => 'Focuses on the adventures of heroes in imaginary lands, often emphasizing their character development and heroic deeds.'],
              ['name' => 'Magical Realism', 'description' => 'Integrates magical elements into a realistic setting, blurring the lines between the fantastical and the real world.'],
              ['name' => 'Comic Fantasy', 'description' => 'Incorporates humor and comedic elements into fantasy settings and narratives, often parodying typical fantasy conventions.'],
              ['name' => 'Romantic Fantasy', 'description' => 'Blends elements of fantasy with romantic plots, focusing on relationships and love stories in magical settings.'],
              ['name' => 'Historical Fantasy', 'description' => 'Set in a historical period but with fantasy elements such as magic or mythical creatures interwoven into historical facts.'],
              ['name' => 'Steampunk', 'description' => 'Combines fantasy with elements of steam-powered machinery and technology, often set in an alternate history or Victorian era.'],
              ['name' => 'Fantasy Adventure', 'description' => 'Involves quests and adventures in fantastical settings, often featuring a group of characters on a journey.'],
              ['name' => 'Superhero Fantasy', 'description' => 'Centers on characters with supernatural powers or abilities, often set in a world where such powers are possible.'],
              ['name' => 'Science Fantasy', 'description' => 'Merges elements of science fiction and fantasy, featuring advanced technology alongside magical elements.'],
          ],
          'Foreign Language' => [
              ['name' => 'Foreign Drama', 'description' => 'Dramatic films from various countries, offering diverse cultural perspectives and storytelling styles.'],
              ['name' => 'Foreign Comedy', 'description' => 'Comedy films that provide insight into humor and cultural nuances from different countries.'],
              ['name' => 'Foreign Action', 'description' => 'Action films showcasing diverse approaches to action sequences, stunts, and cinematic styles from around the world.'],
              ['name' => 'Foreign Romance', 'description' => 'Romantic films that explore love stories and relationships across different cultures and societal norms.'],
              ['name' => 'Foreign Thriller', 'description' => 'Thriller films from various countries, often incorporating cultural elements into suspenseful and gripping narratives.'],
              ['name' => 'Foreign Horror', 'description' => 'Horror films that reflect diverse cultural fears, myths, and storytelling traditions from around the world.'],
              ['name' => 'Art House Foreign', 'description' => 'Artistic and experimental films from various countries, often characterized by a unique cinematic style and narrative approach.'],
              ['name' => 'Foreign Historical', 'description' => 'Historical films that explore significant events, figures, and periods from different countries and cultures.'],
              ['name' => 'Foreign Documentary', 'description' => 'Documentaries that provide insights into various aspects of life, history, and issues from different countries.'],
              ['name' => 'Foreign Family', 'description' => 'Family-oriented films from different cultures, often exploring universal themes through the lens of different societies.'],
              ['name' => 'Foreign Sci-Fi', 'description' => 'Science fiction films that offer various cultural perspectives on futuristic concepts, technology, and imagination.'],
              ['name' => 'Foreign Fantasy', 'description' => 'Fantasy films based on myths, legends, and folklore from various cultures, often featuring unique storytelling elements.'],
              ['name' => 'Foreign Mystery', 'description' => 'Mystery films that incorporate cultural elements in the narrative, often reflecting different approaches to storytelling.'],
              ['name' => 'Foreign Crime', 'description' => 'Crime films that explore the genre from different cultural viewpoints, often with unique settings and societal contexts.'],
              ['name' => 'Foreign Animation', 'description' => 'Animated films representing a variety of animation styles and stories from different countries.'],
              ['name' => 'Foreign Indie', 'description' => 'Independent films from various countries, often showcasing unique voices and perspectives outside mainstream cinema.'],
              ['name' => 'Foreign Biographical', 'description' => 'Biographical films that tell the life stories of figures from different cultures and historical contexts.'],
              ['name' => 'Foreign Musical', 'description' => 'Musical films featuring diverse music styles and traditions from around the world.'],
              ['name' => 'Foreign War', 'description' => 'War films depicting conflicts and perspectives from different countries, often highlighting lesser-known aspects of global history.'],
              ['name' => 'Foreign LGBTQ+', 'description' => 'Films exploring LGBTQ+ themes and stories from a variety of cultural and societal perspectives.'],
          ],
          'Historical' => [
              ['name' => 'Period Drama', 'description' => 'Set in a particular historical period, focusing on dramatic narratives and character development against a backdrop of historical events.'],
              ['name' => 'Biographical', 'description' => 'Centers on the life story of a historical figure, depicting their achievements, struggles, and impact on history.'],
              ['name' => 'War and Military', 'description' => 'Depicts historical wars and military conflicts, often focusing on battles, military strategies, and the experiences of soldiers.'],
              ['name' => 'Historical Epic', 'description' => 'Large scale films set in historical times, often depicting grand narratives, significant battles, or the rise and fall of empires.'],
              ['name' => 'Historical Romance', 'description' => 'Combines elements of romance with a historical setting, exploring romantic relationships in different historical periods.'],
              ['name' => 'Historical Adventure', 'description' => 'Features adventures set in historical times, often including quests, explorations, or treasure hunts.'],
              ['name' => 'Historical Fantasy', 'description' => 'Blends historical settings with fantasy elements, such as magic, mythical creatures, or alternative histories.'],
              ['name' => 'Historical Mystery', 'description' => 'Involves solving mysteries or crimes in a historical setting, often incorporating real historical figures or events.'],
              ['name' => 'Political and Intrigue', 'description' => 'Focuses on political events, court intrigues, and power struggles in historical contexts.'],
              ['name' => 'Historical Fiction', 'description' => 'Narratives set in the past but featuring fictionalized events, characters, or stories interwoven with historical realities.'],
              ['name' => 'Docudrama', 'description' => 'A dramatized representation of real historical events, blending documentary and dramatic techniques to tell the story.'],
              ['name' => 'Cultural and Social History', 'description' => 'Depicts the cultural and social aspects of a particular historical period, focusing on everyday life, traditions, and societal norms.'],
              ['name' => 'Historical Thriller', 'description' => 'Combines the thriller genre with a historical setting, creating suspense and tension in a historical context.'],
              ['name' => 'Religious and Mythological', 'description' => 'Depicts religious stories, mythological tales, or spiritual figures from history.'],
              ['name' => 'Historical Comedy', 'description' => 'Incorporates comedic elements in a historical setting, often using humor to explore or parody historical events and figures.'],
          ],
          'Horror' => [
              ['name' => 'Supernatural Horror', 'description' => 'Involves supernatural elements such as ghosts, demons, and otherworldly forces that terrify characters and audiences.'],
              ['name' => 'Psychological Horror', 'description' => 'Focuses on the psychological aspects of fear and terror, often delving into the characters\' minds and their inner demons.'],
              ['name' => 'Slasher Horror', 'description' => 'Known for serial killers and gruesome murders, often featuring iconic villains and intense violence.'],
              ['name' => 'Monster Horror', 'description' => 'Centers on monstrous creatures, often mutated or supernatural, terrorizing characters and causing chaos.'],
              ['name' => 'Body Horror', 'description' => 'Explores the transformation and mutilation of the human body, often in grotesque and disturbing ways.'],
              ['name' => 'Found Footage', 'description' => 'Presents the story as if it were discovered film or video recordings, creating a sense of realism and immersion.'],
              ['name' => 'Zombie Horror', 'description' => 'Involves reanimated corpses, often leading to apocalyptic scenarios and survival challenges.'],
              ['name' => 'Cult Horror', 'description' => 'Features cults, secret societies, and ritualistic practices that evoke fear and dread.'],
              ['name' => 'Haunted House Horror', 'description' => 'Takes place in eerie, haunted houses or locations, with malevolent spirits and paranormal activity.'],
              ['name' => 'Survival Horror', 'description' => 'Focuses on characters struggling to survive in life-threatening situations, often in isolated or hostile environments.'],
              ['name' => 'Alien Horror', 'description' => 'Involves extraterrestrial beings as sources of terror and suspense, often exploring themes of invasion and unknown lifeforms.'],
              ['name' => 'Lovecraftian Horror', 'description' => 'Inspired by the works of H.P. Lovecraft, characterized by cosmic horror, ancient gods, and existential dread.'],
              ['name' => 'Vampire Horror', 'description' => 'Centers on vampires and their bloodthirsty nature, often exploring themes of immortality and darkness.'],
              ['name' => 'Witchcraft Horror', 'description' => 'Incorporates witchcraft, occult rituals, and witches as central elements of fear and danger.'],
              ['name' => 'Asian Horror', 'description' => 'Horror films with origins in Asian cultures, often featuring unique supernatural entities and folklore.'],
              ['name' => 'Body Snatcher Horror', 'description' => 'Explores the theme of body invasion, where characters are replaced or possessed by malevolent entities.'],
              ['name' => 'Folk Horror', 'description' => 'Takes place in rural or isolated communities with dark traditions, often involving nature and ancient beliefs.'],
              ['name' => 'Campy Horror', 'description' => 'Deliberately uses humor and over-the-top elements while still delivering scares, often in a self-aware manner.'],
              ['name' => 'Horror Anthology', 'description' => 'Presents a collection of horror stories within a single film, often with a common theme or framing narrative.'],
          ],
          'Indie' => [
              ['name' => 'Indie Drama', 'description' => 'Focuses on realistic characters, dialogues, and personal stories, often exploring emotional and intimate narratives.'],
              ['name' => 'Indie Comedy', 'description' => 'Typically features offbeat, quirky humor, often with more emphasis on character development and witty dialogues than on plot.'],
              ['name' => 'Indie Romance', 'description' => 'Centers on unconventional and often more realistic portrayals of relationships and love, deviating from mainstream romance clichés.'],
              ['name' => 'Indie Horror', 'description' => 'Often explores unique and unconventional horror themes, relying more on atmosphere and psychological tension than on big-budget effects.'],
              ['name' => 'Indie Sci-Fi', 'description' => 'Focuses on imaginative and thought-provoking science fiction themes, often with a lower reliance on special effects and a higher emphasis on narrative.'],
              ['name' => 'Indie Thriller', 'description' => 'Includes suspenseful and gripping stories that are more character-driven and often feature psychological or crime-related plots.'],
              ['name' => 'Mumblecore', 'description' => 'Characterized by naturalistic acting and dialogue, low-budget film production, an emphasis on personal relationships, and improvised scripts.'],
              ['name' => 'Art House', 'description' => 'Focuses on an artistic and experimental approach to filmmaking, often characterized by unconventional narrative structures and visual style.'],
              ['name' => 'Indie Documentary', 'description' => 'Documentaries produced with an independent vision, often exploring unique subjects or telling stories from an unconventional perspective.'],
              ['name' => 'Cult Indie', 'description' => 'Indie films that have gained a cult following, often due to their quirky, unconventional, or challenging content.'],
              ['name' => 'Indie Fantasy', 'description' => 'Explores fantasy elements in a more grounded, realistic manner, often blending magical elements with everyday life.'],
              ['name' => 'Indie Historical', 'description' => 'Centers on historical narratives told from a unique, often more personal or localized perspective.'],
              ['name' => 'Indie Adventure', 'description' => 'Adventure films that focus on character development and personal journey more than action and spectacle.'],
              ['name' => 'Indie Mystery', 'description' => 'Mystery films that focus on storytelling and character exploration, often with unconventional narrative techniques.'],
              ['name' => 'Indie Musical', 'description' => 'Musicals produced independently, often featuring original or unconventional music and storytelling styles.'],
              ['name' => 'Indie Family', 'description' => 'Family-oriented films that offer an alternative to mainstream family movies, often with more depth in storytelling and character development.'],
          ],
          'LGBTQ+' => [
              ['name' => 'LGBTQ+ Drama', 'description' => 'Dramatic films exploring the complexities, challenges, and triumphs of LGBTQ+ lives and relationships.'],
              ['name' => 'LGBTQ+ Comedy', 'description' => 'Comedic films that often explore LGBTQ+ themes through humor, satire, and wit, providing both entertainment and social commentary.'],
              ['name' => 'LGBTQ+ Romance', 'description' => 'Romantic films focusing on LGBTQ+ relationships and love stories, encompassing a range of emotional and romantic experiences.'],
              ['name' => 'LGBTQ+ Coming of Age', 'description' => 'Centers on the experiences of LGBTQ+ youth, exploring themes of identity, self-discovery, and the challenges of adolescence.'],
              ['name' => 'LGBTQ+ Documentary', 'description' => 'Documentaries that explore LGBTQ+ histories, issues, and lives, providing insights into diverse experiences and stories.'],
              ['name' => 'LGBTQ+ Historical', 'description' => 'Films set in historical contexts, exploring the lives and experiences of LGBTQ+ individuals in different historical periods.'],
              ['name' => 'LGBTQ+ Biographical', 'description' => 'Biographical films that tell the life stories of notable LGBTQ+ figures, highlighting their contributions and personal journeys.'],
              ['name' => 'LGBTQ+ Fantasy', 'description' => 'Fantasy films with LGBTQ+ themes or characters, incorporating elements of magic, mythology, or speculative fiction.'],
              ['name' => 'LGBTQ+ Sci-Fi', 'description' => 'Science fiction films that include LGBTQ+ characters or themes, often exploring speculative and futuristic concepts.'],
              ['name' => 'LGBTQ+ Thriller', 'description' => 'Thriller films with LGBTQ+ elements, often involving suspense, mystery, and intense emotional narratives.'],
              ['name' => 'LGBTQ+ Horror', 'description' => 'Horror films that incorporate LGBTQ+ themes, characters, or metaphors, often exploring fears and societal tensions.'],
              ['name' => 'Queer Cinema', 'description' => 'Films that specifically focus on queer identities and stories, often challenging traditional narratives and forms.'],
              ['name' => 'LGBTQ+ Activism', 'description' => 'Films focusing on LGBTQ+ activism, rights movements, and the fight for equality and recognition.'],
              ['name' => 'LGBTQ+ Experimental', 'description' => 'Experimental films that explore LGBTQ+ themes in unconventional or avant-garde ways.'],
              ['name' => 'LGBTQ+ Short Films', 'description' => 'Short films that explore a variety of LGBTQ+ stories and themes in a concise format.'],
              ['name' => 'Transgender Stories', 'description' => 'Films that focus specifically on the experiences, lives, and challenges of transgender individuals.'],
              ['name' => 'LGBTQ+ Family', 'description' => 'Films exploring the dynamics of LGBTQ+ families, including parenting, family relationships, and acceptance.'],
              ['name' => 'LGBTQ+ Musical', 'description' => 'Musical films that incorporate LGBTQ+ narratives, often featuring music as a key element of storytelling and expression.'],
              ['name' => 'Gay Cinema', 'description' => 'Films primarily focused on gay characters and stories, exploring a range of experiences and genres.'],
              ['name' => 'Lesbian Cinema', 'description' => 'Films that specifically explore lesbian characters and narratives, across various genres and themes.'],
          ],
          'Musical' => [
              ['name' => 'Classic Musical', 'description' => 'Traditional musicals often featuring elaborate song and dance numbers, focusing on romance, drama, and iconic musical performances.'],
              ['name' => 'Contemporary Musical', 'description' => 'Modern musicals with contemporary music styles and themes, often reflecting current societal issues and trends.'],
              ['name' => 'Animated Musical', 'description' => 'Musicals produced in animation, often family-friendly, with memorable songs and characters.'],
              ['name' => 'Rock Musical', 'description' => 'Musicals featuring rock music, often with a rebellious or edgy tone, portraying rock culture and themes.'],
              ['name' => 'Jukebox Musical', 'description' => 'Musicals built around a selection of songs from a particular band or genre, often integrating existing popular music into the narrative.'],
              ['name' => 'Romantic Musical', 'description' => 'Musicals with a strong emphasis on romantic plots and relationships, interwoven with musical numbers.'],
              ['name' => 'Comedy Musical', 'description' => 'Musicals that blend musical performances with comedic elements, often featuring humorous songs and lighthearted narratives.'],
              ['name' => 'Drama Musical', 'description' => 'Musicals with a more serious tone, focusing on dramatic storytelling, character development, and often tackling complex themes.'],
              ['name' => 'Biographical Musical', 'description' => 'Based on the life story of a real individual, often a famous musician or composer, featuring songs associated with or inspired by them.'],
              ['name' => 'Fantasy and Fairy Tale Musical', 'description' => 'Musicals set in fantastical worlds or based on fairy tales, often featuring magical elements and whimsical musical numbers.'],
              ['name' => 'Historical and Period Musical', 'description' => 'Set in a specific historical period, featuring music and costumes reflective of that time, often interweaving historical events into the plot.'],
              ['name' => 'Opera and Operetta', 'description' => 'Musicals with a classical approach, often based on traditional operas or operettas, featuring orchestral music and operatic singing.'],
              ['name' => 'Cult and Experimental Musical', 'description' => 'Musicals with unconventional or avant-garde elements, often gaining a cult following for their unique approach to the genre.'],
              ['name' => 'Musical Revue', 'description' => 'A collection of musical performances, often without a unifying narrative, showcasing talent and musical numbers.'],
              ['name' => 'Stage Adaptation Musical', 'description' => 'Film adaptations of popular stage musicals, translating the theatrical experience into a cinematic form.'],
          ],
          'Mystery' => [
              ['name' => 'Classic Mystery', 'description' => 'Involves traditional mystery narratives, often featuring detectives, clues, and puzzling scenarios.'],
              ['name' => 'Crime Mystery', 'description' => 'Centers around a crime, typically a murder or a major theft, with a focus on solving the crime and uncovering the perpetrator.'],
              ['name' => 'Psychological Mystery', 'description' => 'Focuses on the psychological aspects of characters, often involving complex mental states, perception, and unreliable narrators.'],
              ['name' => 'Thriller Mystery', 'description' => 'Combines elements of suspense and tension with a mystery plot, often leading to an unexpected or shocking conclusion.'],
              ['name' => 'Noir Mystery', 'description' => 'Characterized by a dark, cynical mood, involving crime, moral ambiguity, and complex character motivations.'],
              ['name' => 'Supernatural Mystery', 'description' => 'Incorporates elements of the supernatural or unexplainable phenomena as part of the mystery.'],
              ['name' => 'Historical Mystery', 'description' => 'Set in a historical period, often involving mysteries related to historical events, figures, or settings.'],
              ['name' => 'Cozy Mystery', 'description' => 'A subgenre of crime fiction where violence and suspense are downplayed, often set in small communities.'],
              ['name' => 'Legal Mystery', 'description' => 'Involves legal processes and courtroom drama, often with a mystery to solve that is central to a court case.'],
              ['name' => 'Medical Mystery', 'description' => 'Centers around a medical problem or condition, often involving a search for a diagnosis or a cure.'],
              ['name' => 'Adventure Mystery', 'description' => 'Combines elements of adventure with a mystery plot, often involving quests or explorations to uncover secrets.'],
              ['name' => 'Paranormal Mystery', 'description' => 'Involves paranormal or supernatural events, often with a protagonist trying to understand or resolve these mysterious occurrences.'],
              ['name' => 'Spy Mystery', 'description' => 'Focuses on espionage and intelligence-gathering, often with complex plots and hidden agendas.'],
              ['name' => 'Sci-Fi Mystery', 'description' => 'Blends science fiction elements with mystery, often involving futuristic or technological scenarios.'],
              ['name' => 'Detective Mystery', 'description' => 'Centers on a detective, either professional or amateur, solving a mystery or series of mysteries.'],
              ['name' => 'Murder Mystery', 'description' => 'Typically involves a murder at the outset and the subsequent process of deducing the murderer’s identity.'],
              ['name' => 'Whodunit', 'description' => 'A subgenre of mystery where the primary goal is to find out who committed the crime, often involving a list of suspects with motives.'],
              ['name' => 'Locked Room Mystery', 'description' => 'Involves a crime committed under seemingly impossible circumstances, such as a murder in a locked room with no apparent exit or entry.'],
              ['name' => 'Conspiracy Mystery', 'description' => 'Revolves around a central plot or conspiracy, often involving political or large-scale secretive plots.'],
              ['name' => 'Occult Mystery', 'description' => 'Involves mysteries surrounding the occult, witchcraft, and mystical phenomena.'],
          ],
          'Noir' => [
              ['name' => 'Classic Noir', 'description' => 'Features the traditional elements of noir, including a cynical attitude, moral ambiguity, complex characters, and a stark visual style.'],
              ['name' => 'Neo-Noir', 'description' => 'A contemporary take on the classic noir genre, often incorporating modern themes and visual styles while maintaining the essence of noir.'],
              ['name' => 'Film Noir', 'description' => 'Refers to the classic Hollywood crime dramas of the 1940s and 1950s, known for their dark, pessimistic tone and shadowy aesthetics.'],
              ['name' => 'Hardboiled Noir', 'description' => 'Centers around a tough, cynical character, often a detective or antihero, involved in a crime or mystery.'],
              ['name' => 'Psychological Noir', 'description' => 'Focuses on the psychological aspects of characters, exploring their inner conflicts, moral dilemmas, and dark pasts.'],
              ['name' => 'Detective Noir', 'description' => 'Involves a detective or investigator as the main character, often entangled in a complex, suspenseful plot.'],
              ['name' => 'Gangster Noir', 'description' => 'Combines elements of gangster films with noir, focusing on organized crime, moral ambiguity, and gritty urban settings.'],
              ['name' => 'Femme Fatale Noir', 'description' => 'Features a mysterious and seductive female character, whose charms ensnare her lovers in dangerous situations.'],
              ['name' => 'Romantic Noir', 'description' => 'Incorporates elements of romance into the noir narrative, often involving doomed relationships or love triangles.'],
              ['name' => 'Sci-Fi Noir', 'description' => 'Blends science fiction elements with noir, often featuring dystopian futures, technological themes, and noir aesthetics.'],
              ['name' => 'Horror Noir', 'description' => 'Integrates horror elements into the noir genre, creating a dark and eerie atmosphere with suspenseful and frightening plots.'],
              ['name' => 'Comedy Noir', 'description' => 'A noir film that incorporates comedic elements, often through witty dialogues, satirical narratives, or dark humor.'],
              ['name' => 'Action Noir', 'description' => 'Combines the action genre with noir, featuring fast-paced sequences, crime elements, and the typical visual style of noir.'],
              ['name' => 'Political Noir', 'description' => 'Involves a political plot or backdrop, often exploring corruption, power struggles, and a cynical view of the political landscape.'],
              ['name' => 'Urban Noir', 'description' => 'Set in urban landscapes, often depicting the dark underbelly of city life, with crime, corruption, and complex characters.'],
              ['name' => 'Rural Noir', 'description' => 'Noir set in rural or small-town settings, presenting a contrast to the typical urban backdrop of classic noir.'],
              ['name' => 'Period Noir', 'description' => 'Set in a specific historical period, often capturing the mood, style, and social issues of that era within a noir framework.'],
              ['name' => 'International Noir', 'description' => 'Noir films from around the world, offering diverse cultural perspectives while adhering to the noir genre\'s themes and style.'],
              ['name' => 'Experimental Noir', 'description' => 'Features unconventional narrative techniques, visual styles, or thematic explorations within the noir genre.'],
              ['name' => 'Jazz Noir', 'description' => 'Incorporates jazz music prominently in its soundtrack, often enhancing the moody and improvisational feel of noir.'],
          ],
          'Romance' => [
              ['name' => 'Classic Romance', 'description' => 'Traditional romance stories often focusing on the emotional aspects of love and relationships, typically featuring timeless romantic themes.'],
              ['name' => 'Romantic Comedy', 'description' => 'Combines elements of humor with romance, often involving lighthearted love stories, humorous misunderstandings, and charming courtships.'],
              ['name' => 'Romantic Drama', 'description' => 'More serious and emotional romantic stories, often dealing with complex relationships, love triangles, and heartfelt drama.'],
              ['name' => 'Historical Romance', 'description' => 'Set in a historical setting, these films explore romantic relationships against the backdrop of historical events or periods.'],
              ['name' => 'Teen Romance', 'description' => 'Focuses on young love and romantic experiences among teenagers, often exploring themes of first love, friendship, and coming of age.'],
              ['name' => 'Romantic Fantasy', 'description' => 'Blends elements of fantasy with romance, often involving magical or supernatural elements as part of the love story.'],
              ['name' => 'Romantic Thriller', 'description' => 'Incorporates elements of suspense or mystery in a romantic context, often involving dangerous situations or romantic intrigue.'],
              ['name' => 'Erotic Romance', 'description' => 'Focuses on romantic relationships with an emphasis on sexual expression and exploration, often with explicit content.'],
              ['name' => 'Romantic Musical', 'description' => 'Musical films where the central theme is romance, featuring songs and music that enhance the romantic storyline.'],
              ['name' => 'Romantic Period Piece', 'description' => 'Romance films set in a specific historical period, emphasizing the romantic ideals and aesthetics of that era.'],
              ['name' => 'Romantic Adventure', 'description' => 'Combines romance with adventure, often featuring couples experiencing adventures and challenges together.'],
              ['name' => 'Romantic Sci-Fi', 'description' => 'Science fiction films with a significant focus on romance, often exploring relationships in futuristic or alternative settings.'],
              ['name' => 'Paranormal Romance', 'description' => 'Centers on romantic relationships involving supernatural beings or phenomena, like vampires, werewolves, or ghosts.'],
              ['name' => 'Chick Flick', 'description' => 'Geared primarily towards a female audience, focusing on romance, personal relationships, and emotion-driven plots.'],
              ['name' => 'International Romance', 'description' => 'Romance films that showcase love stories from around the world, often exploring cross-cultural relationships and global settings.'],
          ],
          'Science Fiction' => [
              ['name' => 'Space Opera', 'description' => 'Grand, dramatic adventures set in outer space, often featuring epic battles, interstellar travel, and complex narratives.'],
              ['name' => 'Cyberpunk', 'description' => 'Futuristic settings focusing on high-tech and low-life, often exploring themes of artificial intelligence, cybernetics, and dystopian societies.'],
              ['name' => 'Dystopian', 'description' => 'Depicts imagined futures with negative, oppressive societal elements, often critiquing current trends, social systems, or political ideologies.'],
              ['name' => 'Post-Apocalyptic', 'description' => 'Set in worlds after major catastrophes, focusing on survival, the breakdown of society, and the aftermath of destruction.'],
              ['name' => 'Time Travel', 'description' => 'Involving the concept of moving between different points in time, exploring the consequences and paradoxes of time travel.'],
              ['name' => 'Alien Invasion', 'description' => 'Centers on extraterrestrial beings invading Earth, often leading to conflicts between humans and aliens.'],
              ['name' => 'Robot and AI', 'description' => 'Focuses on robots, artificial intelligence, and their interactions with humans, exploring themes of technology and consciousness.'],
              ['name' => 'Sci-Fi Thriller', 'description' => 'Combines science fiction elements with suspense and tension, often featuring futuristic technology or scientific concepts.'],
              ['name' => 'Sci-Fi Horror', 'description' => 'Blends science fiction with horror elements, often involving terrifying alien creatures, deadly technologies, or fear-inducing futuristic scenarios.'],
              ['name' => 'Space Western', 'description' => 'Fusing elements of space science fiction with the style and themes of Westerns, set in rugged, space frontier environments.'],
              ['name' => 'Superhero', 'description' => 'Centered around characters with superhuman abilities or powers, often set in a universe where such phenomena are commonplace.'],
              ['name' => 'Utopian', 'description' => 'Depicts idealized and perfect societies, often in contrast to dystopian narratives, exploring the possibilities of a harmonious future.'],
              ['name' => 'Steampunk', 'description' => 'Combines science fiction with 19th-century industrial steam-powered machinery, set in an alternative history or parallel universe.'],
              ['name' => 'Military Sci-Fi', 'description' => 'Focuses on military themes and concepts in a science fiction setting, often involving space warfare and futuristic weaponry.'],
              ['name' => 'Sci-Fi Mystery', 'description' => 'Involves solving mysteries or uncovering secrets in a science fiction setting, often incorporating futuristic technology and scientific concepts.'],
              ['name' => 'Sci-Fi Adventure', 'description' => 'Features adventures in futuristic or extraterrestrial settings, combining elements of exploration, discovery, and thrilling escapades.'],
              ['name' => 'Sci-Fi Drama', 'description' => 'Centers on human experiences and emotional narratives within a science fiction context, often exploring moral and philosophical questions.'],
              ['name' => 'Sci-Fi Comedy', 'description' => 'Incorporates humor and comedic elements into a science fiction setting, often parodying sci-fi conventions or exploring absurd scenarios.'],
              ['name' => 'Hard Science Fiction', 'description' => 'Emphasizes scientific accuracy, technical detail, and logical consistency, often focusing on scientific exploration and discovery.'],
              ['name' => 'Soft Science Fiction', 'description' => 'More focused on social sciences, psychology, and human behavior, often exploring societal and cultural aspects in futuristic settings.'],
          ],
          'Short Film' => [
              ['name' => 'Short Drama', 'description' => 'Focuses on dramatic and emotional storytelling, often exploring complex characters and narratives within a constrained timeframe.'],
              ['name' => 'Short Comedy', 'description' => 'Features brief comedic sketches or stories, often characterized by quick wit, humor, and sometimes satire.'],
              ['name' => 'Short Documentary', 'description' => 'Non-fiction films offering insights into various topics, presented in a concise format, often educational or exploratory in nature.'],
              ['name' => 'Short Animation', 'description' => 'Animated films in a shorter format, showcasing diverse animation styles and storytelling techniques.'],
              ['name' => 'Experimental Short', 'description' => 'Pushes the boundaries of conventional filmmaking, often with abstract or unconventional narrative and visual styles.'],
              ['name' => 'Short Horror', 'description' => 'Conveys suspense, fear, and horror elements in a brief format, often relying on atmosphere and visual storytelling.'],
              ['name' => 'Short Sci-Fi', 'description' => 'Presents science fiction narratives, exploring futuristic concepts and imaginative scenarios in a concise manner.'],
              ['name' => 'Short Fantasy', 'description' => 'Features elements of fantasy, magic, and mythical storytelling in a shorter film format.'],
              ['name' => 'Music Video', 'description' => 'Combines music and film, often serving as a visual interpretation or accompaniment to a song.'],
              ['name' => 'Short Thriller', 'description' => 'Delivers suspense and intense storytelling, often with a twist or a climactic revelation.'],
              ['name' => 'Short Romance', 'description' => 'Explores romantic narratives and relationships in a brief, often poignant format.'],
              ['name' => 'Micro-Short', 'description' => 'Extremely short films, often lasting only a few minutes, focusing on a single, impactful idea or concept.'],
              ['name' => 'Short Adventure', 'description' => 'Presents adventure stories, often showcasing journeys, explorations, or unique experiences in a compact form.'],
              ['name' => 'Short Mystery', 'description' => 'Involves unraveling a mystery or a puzzle, offering a condensed version of intrigue and discovery.'],
              ['name' => 'Short Family', 'description' => 'Family-friendly films in a short format, suitable for viewers of all ages, often with moral or educational themes.'],
              ['name' => 'Short Biography', 'description' => 'Tells the story of a person\'s life or a specific event in their life, condensed into a short narrative format.'],
              ['name' => 'Short War', 'description' => 'Depicts stories of conflict, war, and its effects in a brief, often poignant or reflective manner.'],
              ['name' => 'Short Crime', 'description' => 'Focuses on crime stories, including investigations, criminal perspectives, or the impact of crime, presented briefly.'],
              ['name' => 'Student Film', 'description' => 'Created by film students, often experimental or showcasing emerging talent and fresh perspectives.'],
              ['name' => 'Silent Short', 'description' => 'Modern or historical films made without synchronized sound, focusing on visual storytelling and expression.'],
          ],
          'Silent Film' => [
              ['name' => 'Silent Comedy', 'description' => 'Features physical comedy and slapstick, relying on visual gags and expressions, exemplified by actors like Charlie Chaplin and Buster Keaton.'],
              ['name' => 'Silent Drama', 'description' => 'Dramatic films that convey emotional narratives through expressive acting, visuals, and title cards, often dealing with intense and serious themes.'],
              ['name' => 'Silent Romance', 'description' => 'Centers on romantic stories, showcasing emotional expressions and relationships without spoken dialogue.'],
              ['name' => 'Silent Adventure', 'description' => 'Adventure films of the era, often featuring epic journeys, exotic locations, and daring feats, told through visual storytelling.'],
              ['name' => 'Silent Horror', 'description' => 'Horror films relying on atmosphere, visual effects, and makeup, often creating a sense of dread and suspense without sound.'],
              ['name' => 'Silent Sci-Fi', 'description' => 'Science fiction films presenting futuristic or imaginative themes through creative visuals and innovative special effects.'],
              ['name' => 'Silent Fantasy', 'description' => 'Fantasy films that use imaginative storytelling and special effects to create magical and mythical worlds.'],
              ['name' => 'Silent Historical', 'description' => 'Historical films portraying significant events or periods, often with elaborate sets and costumes to recreate the past.'],
              ['name' => 'Silent War', 'description' => 'War films depicting military conflicts and battles, often focusing on visuals and action sequences to convey the story.'],
              ['name' => 'Silent Western', 'description' => 'Westerns from the silent film era, featuring cowboys, outlaws, and frontier life, told through action and visual storytelling.'],
              ['name' => 'Silent Crime', 'description' => 'Crime films focusing on criminals, detectives, and suspenseful plots, using visual cues and title cards to unfold the story.'],
              ['name' => 'Silent Mystery', 'description' => 'Mystery films that build suspense and intrigue through visual storytelling, often involving detectives and puzzling scenarios.'],
              ['name' => 'Silent Documentary', 'description' => 'Documentaries of the era, presenting real-life events, people, and places through silent footage and title descriptions.'],
              ['name' => 'Silent Experimental', 'description' => 'Experimental films exploring new techniques in storytelling, visuals, and special effects, pushing the boundaries of cinema.'],
              ['name' => 'Silent Biographical', 'description' => 'Biographical films depicting the lives of historical figures, using visual narratives to portray their stories.'],
              ['name' => 'Silent Art Film', 'description' => 'Artistic films focusing on visual composition, symbolism, and innovative filmmaking techniques.'],
              ['name' => 'Silent Melodrama', 'description' => 'Melodramatic films characterized by sensational storytelling, expressive acting, and dramatic plots.'],
              ['name' => 'Silent Serial', 'description' => 'Serial films consisting of short episodes, often featuring cliffhangers and adventurous plots.'],
              ['name' => 'Silent Comedy-Drama', 'description' => 'Films that blend comedic and dramatic elements, showcasing a range of emotional storytelling through visuals.'],
              ['name' => 'Silent Avant-Garde', 'description' => 'Avant-garde films that experiment with narrative structures, visual techniques, and unconventional storytelling.'],
          ],
          'Superhero' => [
              ['name' => 'Classic Superhero', 'description' => 'Centers on traditional superhero narratives with characters possessing extraordinary abilities, often fighting against villains to save the world.'],
              ['name' => 'Comic Book Adaptation', 'description' => 'Films adapted from comic books, featuring popular superhero characters and stories from graphic novels and comics.'],
              ['name' => 'Dark Superhero', 'description' => 'Features a grittier, darker tone, focusing on more complex moral issues and often portraying more brooding or conflicted heroes.'],
              ['name' => 'Sci-Fi Superhero', 'description' => 'Blends science fiction elements with superhero themes, often involving advanced technology, alien worlds, or futuristic settings.'],
              ['name' => 'Fantasy Superhero', 'description' => 'Incorporates elements of fantasy, with superheroes existing in worlds where magic or mythical creatures are prevalent.'],
              ['name' => 'Animated Superhero', 'description' => 'Superhero films in animated format, ranging from traditional animation to CGI, often appealing to a wider age range including younger audiences.'],
              ['name' => 'Action Superhero', 'description' => 'Focuses heavily on high-octane action sequences, spectacular fight scenes, and thrilling stunts.'],
              ['name' => 'Superhero Team', 'description' => 'Centers on a group of superheroes working together, often featuring ensemble casts and team dynamics.'],
              ['name' => 'Superheroine', 'description' => 'Focuses on female superheroes, highlighting their stories, struggles, and triumphs.'],
              ['name' => 'Anti-Hero', 'description' => 'Features protagonists who lack conventional heroic qualities, often blurring the lines between hero and villain.'],
              ['name' => 'Superhero Comedy', 'description' => 'Blends superhero themes with comedic elements, often parodying typical superhero conventions or featuring humorous characters and situations.'],
              ['name' => 'Family Superhero', 'description' => 'Family-friendly superhero films, suitable for all ages, often with themes of teamwork, friendship, and moral lessons.'],
              ['name' => 'Psychological Superhero', 'description' => 'Explores the psychological aspects of being a superhero, including the personal and emotional challenges faced by the characters.'],
              ['name' => 'Crossover Superhero', 'description' => 'Features characters from different superhero universes coming together, often in a shared cinematic universe.'],
              ['name' => 'Dystopian Superhero', 'description' => 'Set in dystopian futures where superheroes face bleak, challenging environments and complex moral dilemmas.'],
              ['name' => 'Origin Story', 'description' => 'Focuses on the backstory of a superhero, exploring how they gained their powers and their journey to becoming a hero.'],
              ['name' => 'Superhero Sequel/Prequel', 'description' => 'Continuations or prequels to existing superhero films, expanding on the universe and characters’ stories.'],
              ['name' => 'International Superhero', 'description' => 'Superhero films originating from various countries, showcasing different cultural takes on the superhero genre.'],
              ['name' => 'Indie Superhero', 'description' => 'Independent superhero films, often with lower budgets and a focus on storytelling over special effects.'],
              ['name' => 'Mythological Superhero', 'description' => 'Superheroes rooted in mythology, often drawing on ancient legends and mythological heroes.'],
          ],
          'Thriller' => [
              ['name' => 'Psychological Thriller', 'description' => 'Focuses on the psychological states of characters, involving suspense, anxiety, and complex psychological conflicts.'],
              ['name' => 'Crime Thriller', 'description' => 'Centers on criminal activities, often featuring detectives or criminals as main characters, with a focus on the pursuit and investigation of crime.'],
              ['name' => 'Mystery Thriller', 'description' => 'Involves solving a mystery, often with twists and turns, focusing on the intellectual challenge of piecing together clues and evidence.'],
              ['name' => 'Action Thriller', 'description' => 'Combines elements of action with suspense, often featuring fast-paced sequences, high stakes, and adrenaline-pumping scenes.'],
              ['name' => 'Political Thriller', 'description' => 'Set against the backdrop of political intrigue, often involving government conspiracies, espionage, and power struggles.'],
              ['name' => 'Spy Thriller', 'description' => 'Focuses on espionage and the world of spies, involving secret missions, covert operations, and international intrigue.'],
              ['name' => 'Legal Thriller', 'description' => 'Set within the context of the legal system, involving lawyers, trials, and legal battles, often with a focus on justice and moral dilemmas.'],
              ['name' => 'Sci-Fi Thriller', 'description' => 'Blends science fiction elements with suspense, often involving futuristic technology, scientific discoveries, or dystopian worlds.'],
              ['name' => 'Horror Thriller', 'description' => 'Combines elements of horror with the thriller genre, often involving terrifying situations, fear-inducing antagonists, and suspenseful scenarios.'],
              ['name' => 'Erotic Thriller', 'description' => 'Involves sexual relationships and erotic themes, often intertwined with elements of suspense, danger, and betrayal.'],
              ['name' => 'Noir Thriller', 'description' => 'Characterized by a dark, moody atmosphere, involving crime, moral ambiguity, and complex characters.'],
              ['name' => 'Techno Thriller', 'description' => 'Centers around technology and its impact, often featuring advanced technology, cybernetics, and computer hacking.'],
              ['name' => 'Supernatural Thriller', 'description' => 'Incorporates elements of the supernatural, often blending mystery and suspense with paranormal phenomena.'],
              ['name' => 'Medical Thriller', 'description' => 'Set in the world of medicine, involving medical crises, diseases, and the ethical dilemmas faced by the medical community.'],
              ['name' => 'Financial Thriller', 'description' => 'Focuses on the world of finance, involving corporate conspiracies, economic crimes, and the high stakes of the financial industry.'],
              ['name' => 'Adventure Thriller', 'description' => 'Combines elements of adventure with suspense, often featuring journeys, explorations, and survival in dangerous settings.'],
              ['name' => 'Disaster Thriller', 'description' => 'Centers around catastrophic events and disasters, often focusing on survival, rescue efforts, and the aftermath of disasters.'],
              ['name' => 'Ecological Thriller', 'description' => 'Involves environmental themes and ecological dangers, often highlighting the impact of human activities on nature.'],
              ['name' => 'Conspiracy Thriller', 'description' => 'Revolves around conspiracies, secret societies, and hidden agendas, often uncovering a larger, sinister plot.'],
              ['name' => 'Historical Thriller', 'description' => 'Set in a historical context, combining elements of suspense and intrigue with historical events and figures.'],
          ],
          'War' => [
              ['name' => 'World War II', 'description' => 'Centers on the events of World War II, often depicting battles, soldier experiences, and significant historical figures of that era.'],
              ['name' => 'World War I', 'description' => 'Focuses on World War I, covering the trench warfare, historical battles, and the overall impact of the war on soldiers and society.'],
              ['name' => 'Modern Warfare', 'description' => 'Depicts contemporary military conflicts, often exploring themes of modern combat, technology in warfare, and current geopolitical issues.'],
              ['name' => 'Vietnam War', 'description' => 'Set during the Vietnam War, these films often explore the psychological and moral complexities faced by soldiers and the impact of the war at home and abroad.'],
              ['name' => 'Historical War', 'description' => 'Covers wars from various historical periods, focusing on the historical context, battles, and strategies of those times.'],
              ['name' => 'Civil War', 'description' => 'Revolves around civil wars, exploring the internal conflicts, divisions, and impacts of such wars on countries and societies.'],
              ['name' => 'Revolutionary War', 'description' => 'Focuses on wars of revolution and independence, exploring the struggles, ideologies, and figures behind these historical events.'],
              ['name' => 'Cold War', 'description' => 'Set during the Cold War era, often involving espionage, nuclear threat, and the ideological conflict between the superpowers.'],
              ['name' => 'Naval Warfare', 'description' => 'Centers on naval battles and conflicts, exploring life at sea, naval strategy, and historical naval engagements.'],
              ['name' => 'Air Warfare', 'description' => 'Focused on air combat and the role of air forces in wars, including dogfights, bombing campaigns, and the life of pilots.'],
              ['name' => 'Guerrilla Warfare', 'description' => 'Depicts irregular warfare and guerrilla tactics, often focusing on resistance movements and asymmetric warfare.'],
              ['name' => 'Epic War', 'description' => 'Large-scale war films with grand narratives, often depicting significant battles, wide-ranging conflicts, and epic storytelling.'],
              ['name' => 'War Drama', 'description' => 'Emphasizes the dramatic and human aspect of war, exploring the emotional and psychological effects on individuals and families.'],
              ['name' => 'War Adventure', 'description' => 'Combines elements of adventure with war, often focusing on missions, explorations, and daring exploits in wartime.'],
              ['name' => 'Anti-War', 'description' => 'Critiques or questions the nature and consequences of war, often highlighting the futility, horror, and tragedy of armed conflict.'],
              ['name' => 'War Comedy', 'description' => 'Incorporates comedic elements into war settings, often using satire or dark humor to comment on the absurdities of war.'],
              ['name' => 'Biographical War', 'description' => 'Based on the lives of real individuals in wartime, exploring their experiences, contributions, and personal journeys.'],
              ['name' => 'War Romance', 'description' => 'Focuses on romantic relationships set against the backdrop of war, exploring how love and conflict intersect.'],
              ['name' => 'Propaganda War', 'description' => 'Films created to promote specific political messages or ideologies, often produced during wartime to influence public opinion.'],
              ['name' => 'Prisoner of War', 'description' => 'Centers on the experiences of prisoners of war, exploring themes of captivity, survival, and human resilience.'],
          ],
          'Western' => [
              ['name' => 'Classic Western', 'description' => 'Traditional Westerns featuring iconic elements of the Old West, including cowboys, saloons, and standoffs, often focusing on themes of justice and frontier life.'],
              ['name' => 'Spaghetti Western', 'description' => 'A sub-genre of Western films produced in Europe, characterized by their style, action sequences, and dramatic portrayals.'],
              ['name' => 'Contemporary Western', 'description' => 'Modern takes on the Western genre, often set in current times but retaining elements of the traditional Western setting and themes.'],
              ['name' => 'Revisionist Western', 'description' => 'Challenges the traditional tropes of Westerns, often presenting more morally complex narratives and a realistic portrayal of the Old West.'],
              ['name' => 'Comedy Western', 'description' => 'Blends elements of comedy into the Western setting, often parodying classic Western tropes or featuring humorous storylines.'],
              ['name' => 'Western Drama', 'description' => 'Focuses on dramatic and emotional narratives in the Western setting, exploring in-depth character development and complex relationships.'],
              ['name' => 'Action Western', 'description' => 'Features high-action sequences set in the Western genre, often including gunfights, horse chases, and adventure.'],
              ['name' => 'Western Romance', 'description' => 'Centers on romantic stories set against the backdrop of the Western frontier, exploring love and relationships in the Old West.'],
              ['name' => 'Western Thriller', 'description' => 'Incorporates elements of suspense and tension in a Western setting, often featuring crime, mystery, and pursuit in the frontier.'],
              ['name' => 'Western Horror', 'description' => 'Blends horror elements with the Western genre, often featuring supernatural occurrences or menacing threats in the Old West.'],
              ['name' => 'Historical Western', 'description' => 'Set in specific historical contexts within the Western genre, often based on real historical figures and events.'],
              ['name' => 'Western Musical', 'description' => 'Combines the Western setting with musical elements, featuring songs and performances that reflect the spirit of the Western genre.'],
              ['name' => 'Western Adventure', 'description' => 'Focuses on adventure and exploration in the Western context, often featuring quests, treasure hunts, or exploration of the frontier.'],
              ['name' => 'Outlaw Western', 'description' => 'Centers around outlaws and anti-heroes of the Old West, exploring themes of freedom, rebellion, and the blurred lines of morality.'],
              ['name' => 'Family Western', 'description' => 'Family-friendly Westerns, suitable for all ages, often featuring stories of friendship, adventure, and life lessons in the Western setting.'],
          ],
      ];

      foreach ($subCategoryGroups as $categoryName => $subCategories) {
        $categoryId = $this->getCategoryIdByName($categoryName);
        if ($categoryId) {
          $this->addCategoryId($subCategories, $categoryId);

          // Modify the addTimestamps function to handle a single subCategory
          foreach ($subCategories as $subCategory) {
            try {
              // Add timestamps directly to the subCategory array
              $timestamp = now();
              $subCategory['created_at'] = $timestamp;
              $subCategory['updated_at'] = $timestamp;

              DB::table('movie_category_subs')->insert($subCategory);
            } catch (\Illuminate\Database\QueryException $e) {
              // Handle the exception
              Log::warning("Duplicate entry for subcategory: " . $subCategory['name']);
            }
          }
        }
      }

    }

  private function addTimestamps(array &$items)
  {
    try {
      $timestamp = now();
      foreach ($items as &$item) {
        if (is_array($item)) {
          $item['created_at'] = $timestamp;
          $item['updated_at'] = $timestamp;
        } else {
          // Log the error or handle it as appropriate
          Log::error("Invalid item structure", ['item' => $item]);
        }
      }
    } catch (\Exception $e) {
      // Log the detailed error message for debugging
      Log::error("Error in addTimestamps: " . $e->getMessage());
    }
  }


  private function getCategoryIdByName($categoryName)
  {
    $category = DB::table('movie_categories')->where('name', $categoryName)->first();
    return $category ? $category->id : null;
  }

  private function addCategoryId(&$subCategoryArray, $categoryId)
  {
    foreach ($subCategoryArray as &$subCategory) {
      $subCategory['movie_categories_id'] = $categoryId;
    }
  }
}
