<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewsCategorySubsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      // Example sub-category groups with their respective category names
      $subCategoryGroups = [
          'World News' => [
              ['name' => 'International Politics', 'description' => 'Coverage of global political developments, international relations, and diplomatic affairs.'],
              ['name' => 'Global Economy', 'description' => 'News and analysis on the global economy, trade agreements, and international economic policies.'],
              ['name' => 'Conflicts and Wars', 'description' => 'Reporting on international conflicts, wars, military actions, and peacekeeping efforts.'],
              ['name' => 'Human Rights and Social Issues', 'description' => 'Focus on human rights issues, social movements, and humanitarian crises around the world.'],
              ['name' => 'Environmental and Climate News', 'description' => 'Global environmental issues, climate change impacts, and international sustainability efforts.'],
              ['name' => 'Health and Pandemics', 'description' => 'Updates on global health issues, pandemics, and international public health campaigns.'],
              ['name' => 'Science and Technology Innovations', 'description' => 'Advancements in science and technology, and their impact on a global scale.'],
              ['name' => 'Cultural and Historical Insights', 'description' => 'Exploring cultural stories, historical events, and heritage from around the world.'],
              ['name' => 'Global Sports and Events', 'description' => 'International sports events, competitions, and global athletic achievements.'],
              ['name' => 'International Trade and Markets', 'description' => 'News on international trade, market trends, and global financial markets.'],
              ['name' => 'World Leaders and Diplomacy', 'description' => 'Profiles of world leaders, diplomatic visits, and international summits.'],
              ['name' => 'Global Travel and Tourism', 'description' => 'Trends and news in international travel, tourism, and travel advisories.'],
              ['name' => 'Disasters and Emergency Responses', 'description' => 'Reporting on natural disasters, emergency responses, and relief efforts worldwide.'],
              ['name' => 'International Law and Justice', 'description' => 'Legal issues at the international level, including war crimes, international court rulings, and legal disputes.'],
              ['name' => 'Global Media and Communication', 'description' => 'The role and impact of global media, communication trends, and international journalism.'],
              ['name' => 'Migration and Refugees', 'description' => 'Issues surrounding migration, refugees, asylum seekers, and international migration policies.'],
              ['name' => 'Energy and Resource Management', 'description' => 'Global energy policies, resource management, and international energy trends.'],
              ['name' => 'International Nonprofits and NGOs', 'description' => 'The work and impact of international nonprofits, NGOs, and global charity organizations.'],
              ['name' => 'Space Exploration and Astronomy', 'description' => 'News on space exploration, astronomical discoveries, and international space missions.'],
              ['name' => 'Cultural Exchanges and Globalization', 'description' => 'Exploring cultural exchanges, the effects of globalization, and international collaborations.'],
          ],
          'National News' => [
              ['name' => 'National Politics and Government', 'description' => 'Coverage of the country\'s political developments, governmental policies, and national elections.'],
              ['name' => 'Domestic Economy and Finance', 'description' => 'National economic news, financial markets, fiscal policies, and economic indicators within the country.'],
              ['name' => 'Healthcare and Public Health', 'description' => 'Nationwide health issues, public health campaigns, healthcare policies, and medical advancements.'],
              ['name' => 'Education and National Policies', 'description' => 'News on national educational systems, policies, reforms, and educational trends across the country.'],
              ['name' => 'Environment and Natural Resources', 'description' => 'Environmental concerns, natural resource management, and ecological initiatives within the nation.'],
              ['name' => 'Transportation and Infrastructure', 'description' => 'Developments in national transportation networks, infrastructure projects, and urban planning.'],
              ['name' => 'Law and Justice', 'description' => 'Legal news, nationwide judicial decisions, legal reforms, and high-profile court cases.'],
              ['name' => 'National Security and Defense', 'description' => 'Issues related to national security, defense policies, military operations, and homeland security.'],
              ['name' => 'Cultural Affairs and Heritage', 'description' => 'Exploring national cultural heritage, arts, festivals, and cultural policies across the country.'],
              ['name' => 'Science and Technology in the Nation', 'description' => 'National advancements in science and technology, research initiatives, and technological impacts.'],
              ['name' => 'Social Issues and Movements', 'description' => 'Key social issues, national movements, societal changes, and public demonstrations.'],
              ['name' => 'National Sports and Athletics', 'description' => 'Coverage of national sports events, athletic competitions, and sports-related news within the country.'],
              ['name' => 'Employment and Labor Market', 'description' => 'Insights into the national job market, employment trends, workforce developments, and labor policies.'],
              ['name' => 'Agriculture and Farming', 'description' => 'News on national agriculture, farming trends, food production, and rural development.'],
              ['name' => 'National Celebrities and Personalities', 'description' => 'News and stories about prominent national figures, celebrities, and public personalities.'],
              ['name' => 'Natural Disasters and Emergency Responses', 'description' => 'Reporting on natural disasters, emergency management, and disaster relief efforts within the country.'],
              ['name' => 'Historical Perspectives and National History', 'description' => 'Features on national history, historical events, and retrospective analysis.'],
              ['name' => 'Energy Policies and Power Generation', 'description' => 'National energy strategies, power generation, and discussions on renewable energy sources.'],
              ['name' => 'Tourism and National Attractions', 'description' => 'Information on national tourism, travel destinations, and tourist attractions within the country.'],
              ['name' => 'Public Opinion and National Surveys', 'description' => 'Insights into public opinion, national surveys, and polls reflecting the country\'s sentiment.'],
          ],
          'Local News' => [
              ['name' => 'Local Politics and Government', 'description' => 'Covering local political news, city council, municipal policies, and community governance.'],
              ['name' => 'Local Business and Economy', 'description' => 'Focusing on the local economy, small businesses, and regional market trends.'],
              ['name' => 'Local Health and Environment', 'description' => 'Reporting on community health issues, public health policies, and environmental initiatives.'],
              ['name' => 'Education and Youth', 'description' => 'News on local schools, educational developments, and youth activities in the community.'],
              ['name' => 'Sports and Recreation', 'description' => 'Local sports events, recreational activities, and profiles of regional athletes and teams.'],
              ['name' => 'Arts, Culture, and Entertainment', 'description' => 'Local arts and cultural events, entertainment news, and community festivals.'],
              ['name' => 'Community and Lifestyle', 'description' => 'Stories about community events, neighborhood activities, lifestyle trends, and local human interest.'],
              ['name' => 'Crime, Safety, and Justice', 'description' => 'Reporting on local law enforcement, crime trends, public safety issues, and judicial proceedings.'],
              ['name' => 'Transportation and Infrastructure', 'description' => 'News on local transportation systems, road conditions, public works, and urban development.'],
              ['name' => 'Real Estate and Housing', 'description' => 'Local real estate market, housing developments, urban planning, and zoning issues.'],
              ['name' => 'Weather and Emergency Services', 'description' => 'Local weather forecasts, emergency services updates, and disaster preparedness.'],
              ['name' => 'Local Economy and Employment', 'description' => 'Coverage of the local job market, employment trends, and economic initiatives.'],
              ['name' => 'Local Technology and Science', 'description' => 'Advancements in technology and science within the local community.'],
              ['name' => 'Civic Engagement and Volunteering', 'description' => 'Opportunities and news on civic participation and community volunteering.'],
              ['name' => 'Local History and Heritage', 'description' => 'Exploring the local area\'s history, heritage sites, and conservation efforts.'],
              ['name' => 'Local Nonprofits and Charities', 'description' => 'Highlighting local nonprofit organizations, charity events, and community support programs.'],
              ['name' => 'Neighborhood News', 'description' => 'Updates specific to particular neighborhoods within the region.'],
              ['name' => 'Animal Welfare', 'description' => 'Local animal welfare issues, pet adoption, and wildlife conservation.'],
              ['name' => 'Agriculture and Local Farming', 'description' => 'News on agriculture, local farms, and food sourcing in the region.'],
          ],
          'Politics' => [
              ['name' => 'Domestic Politics', 'description' => 'Covering national political events, policy-making, and domestic governmental affairs.'],
              ['name' => 'International Relations', 'description' => 'Focusing on diplomacy, international agreements, and relations between countries.'],
              ['name' => 'Political Campaigns and Elections', 'description' => 'News about political campaigns, election processes, and voting trends.'],
              ['name' => 'Legislative Developments', 'description' => 'Reporting on the activities of legislative bodies, new laws, and debates in parliament or congress.'],
              ['name' => 'Political Parties and Movements', 'description' => 'Covering the activities, policies, and inner workings of various political parties and movements.'],
              ['name' => 'Political Leaders and Figures', 'description' => 'Profiles and news about prominent politicians, leaders, and influential figures in politics.'],
              ['name' => 'Public Policy and Administration', 'description' => 'Analysis and news on public policy initiatives, administrative changes, and governmental reforms.'],
              ['name' => 'Political Theory and Analysis', 'description' => 'In-depth analysis, commentary, and discussion of political theories and ideologies.'],
              ['name' => 'Civic Participation and Advocacy', 'description' => 'Stories about grassroots movements, civic engagement, and advocacy efforts in the political sphere.'],
              ['name' => 'Geopolitics and Global Issues', 'description' => 'Examining the influence of geography on politics and covering significant global issues and trends.'],
              ['name' => 'Defense and National Security', 'description' => 'News related to national defense, military policies, and security strategies.'],
              ['name' => 'Political Scandals and Controversies', 'description' => 'Reporting on scandals, controversies, and major disputes involving political figures and institutions.'],
              ['name' => 'Government Services and Public Sector', 'description' => 'Information about government services, public sector developments, and administrative changes.'],
              ['name' => 'Human Rights and Liberties', 'description' => 'Coverage of issues related to human rights, civil liberties, and freedom across the world.'],
              ['name' => 'Environmental Policy and Green Politics', 'description' => 'Focusing on environmental legislation, green political movements, and sustainability in policy-making.'],
              ['name' => 'Economic Policy and Regulation', 'description' => 'News on economic policies, financial regulations, and their impact on national and global economies.'],
              ['name' => 'Judicial and Legal Affairs', 'description' => 'Coverage of the judiciary, legal developments, and significant court cases with political implications.'],
              ['name' => 'Political Ethics and Transparency', 'description' => 'Reporting on issues of ethics, transparency, and accountability in politics.'],
              ['name' => 'Social Policy and Welfare', 'description' => 'News regarding social policies, welfare programs, and societal impacts of political decisions.'],
              ['name' => 'Local and Regional Politics', 'description' => 'Focusing on political events and issues at local and regional levels, including municipal and state/provincial politics.'],
          ],
          'Business and Economy' => [
              ['name' => 'Market Trends', 'description' => 'Analysis and news on stock market trends, investment opportunities, and financial markets worldwide.'],
              ['name' => 'Corporate News', 'description' => 'Coverage of major corporate developments, business strategies, and profiles of key business leaders.'],
              ['name' => 'Economic Policies', 'description' => 'Insight into government economic policies, fiscal measures, and their impact on the national and global economy.'],
              ['name' => 'Small Business and Entrepreneurship', 'description' => 'Stories about small businesses, startups, entrepreneurship, and innovative business models.'],
              ['name' => 'Financial Services and Banking', 'description' => 'News related to banking services, financial institutions, and trends in the financial sector.'],
              ['name' => 'International Trade and Commerce', 'description' => 'Coverage of international trade relations, export-import news, and global commerce trends.'],
              ['name' => 'Real Estate and Property Markets', 'description' => 'Information on the real estate market, property investments, and housing trends.'],
              ['name' => 'Consumer Affairs and Retail', 'description' => 'News about consumer trends, retail industry developments, and consumer rights.'],
              ['name' => 'Technology in Business', 'description' => 'How technology influences business operations, digital transformations, and tech industry impacts on business.'],
              ['name' => 'Employment and Labor Market', 'description' => 'Updates on employment trends, job markets, labor laws, and workforce development.'],
              ['name' => 'Energy Sector and Resources', 'description' => 'News about the energy industry, renewable resources, and the environmental impact of energy production.'],
              ['name' => 'Agriculture and Farming Economy', 'description' => 'Coverage of the agricultural sector, farming economy, and related agribusiness news.'],
              ['name' => 'Transportation and Logistics', 'description' => 'Insight into the transportation and logistics industry, including air, sea, and land freight developments.'],
              ['name' => 'Economic Analysis and Opinion', 'description' => 'Expert analysis, opinions, and commentary on economic issues and trends.'],
              ['name' => 'Global Economy', 'description' => 'Reporting on global economic events, international financial systems, and world economic organizations.'],
              ['name' => 'E-Commerce and Online Business', 'description' => 'The growing impact of e-commerce, online marketplaces, and digital business strategies.'],
              ['name' => 'Business Law and Regulations', 'description' => 'Legal aspects of business operations, regulatory changes, and compliance issues.'],
              ['name' => 'Personal Finance and Investment', 'description' => 'Guidance on personal finance, investment strategies, and financial planning.'],
              ['name' => 'Manufacturing and Industry', 'description' => 'News about manufacturing sectors, industrial growth, and production trends.'],
              ['name' => 'Startups and Innovation', 'description' => 'Focus on emerging startups, innovative business ideas, and entrepreneurial ventures.'],
          ],
          'Technology' => [
              ['name' => 'Consumer Electronics', 'description' => 'Latest news on consumer electronics, including smartphones, gadgets, and home devices.'],
              ['name' => 'Software and Apps', 'description' => 'Covering software developments, app updates, and trends in software technology.'],
              ['name' => 'Computing and Hardware', 'description' => 'News about computer hardware, peripherals, and advancements in computing technology.'],
              ['name' => 'Internet and Web Technologies', 'description' => 'Developments in internet technologies, online services, web trends, and cybersecurity.'],
              ['name' => 'Artificial Intelligence and Machine Learning', 'description' => 'Advancements and discussions in AI, machine learning, and their applications.'],
              ['name' => 'Blockchain and Cryptocurrency', 'description' => 'Latest trends in blockchain technology, cryptocurrencies, and the digital economy.'],
              ['name' => 'Virtual and Augmented Reality', 'description' => 'Updates on VR and AR technologies, applications, and immersive experiences.'],
              ['name' => 'Wearable Technology', 'description' => 'Developments in wearable devices, fitness trackers, smartwatches, and health-focused wearables.'],
              ['name' => 'Gaming and Interactive Entertainment', 'description' => 'News about video game technology, gaming consoles, and the gaming industry.'],
              ['name' => 'Space Technology and Exploration', 'description' => 'Advancements in space technology, space exploration missions, and related research.'],
              ['name' => 'Telecommunications', 'description' => 'Updates in the telecommunications industry, including mobile networks, 5G technology, and communication infrastructure.'],
              ['name' => 'Automotive and Transport Tech', 'description' => 'Technological innovations in the automotive industry, including electric vehicles and autonomous driving.'],
              ['name' => 'Green Tech and Sustainability', 'description' => 'Focus on environmentally-friendly technologies, renewable energy, and sustainability in tech.'],
              ['name' => 'Biotechnology and Medical Technology', 'description' => 'Advances in biotech, medical devices, health tech, and the intersection of technology and healthcare.'],
              ['name' => 'Robotics and Automation', 'description' => 'Developments in robotics, automation systems, and their impact on industries and daily life.'],
              ['name' => 'Tech Industry and Market Trends', 'description' => 'Analysis of tech industry trends, market dynamics, and tech company profiles.'],
              ['name' => 'Tech Policy and Regulation', 'description' => 'Legislation, policies, and regulatory issues affecting the tech sector.'],
              ['name' => 'Tech Startups and Entrepreneurship', 'description' => 'Emerging startups in the tech space, venture capital, and entrepreneurial stories.'],
              ['name' => 'Data Science and Analytics', 'description' => 'Insights into data science, big data technologies, and analytics tools and techniques.'],
              ['name' => 'Emerging Technologies', 'description' => 'Coverage of cutting-edge and emerging technologies that are shaping the future.'],
          ],
          'Health' => [
              ['name' => 'Public Health and Safety', 'description' => 'Coverage of public health initiatives, safety guidelines, and health advisories.'],
              ['name' => 'Medical Research and Advances', 'description' => 'Latest developments in medical research, discoveries, and scientific breakthroughs in healthcare.'],
              ['name' => 'Mental Health and Wellness', 'description' => 'Focusing on mental health issues, wellness practices, and psychological well-being.'],
              ['name' => 'Nutrition and Diet', 'description' => 'Advice and news on nutrition, diet trends, healthy eating habits, and dietary supplements.'],
              ['name' => 'Fitness and Exercise', 'description' => 'Tips and news on physical fitness, exercise routines, sports medicine, and active living.'],
              ['name' => 'Healthcare Policy and Legislation', 'description' => 'Discussions on healthcare policies, reforms, insurance, and legal aspects affecting the health sector.'],
              ['name' => 'Diseases and Conditions', 'description' => 'Information on specific diseases, medical conditions, their treatments, and prevention strategies.'],
              ['name' => 'Pharmaceuticals and Drugs', 'description' => 'Updates on pharmaceutical developments, drug approvals, and the pharmaceutical industry.'],
              ['name' => 'Medical Devices and Technology', 'description' => 'Advancements in medical technology, devices, diagnostics, and digital health solutions.'],
              ['name' => 'Women’s Health', 'description' => 'Topics specifically related to women’s health, including reproductive health, gynecology, and maternal health.'],
              ['name' => 'Men’s Health', 'description' => 'Focused on health issues predominantly affecting men, including urology, cardiology, and men’s wellness.'],
              ['name' => 'Child and Adolescent Health', 'description' => 'Coverage of health topics affecting infants, children, and teenagers, including pediatric medicine and adolescent health issues.'],
              ['name' => 'Senior Health and Geriatrics', 'description' => 'Health concerns and medical care for the elderly, focusing on geriatric health and age-related conditions.'],
              ['name' => 'Alternative Medicine and Therapies', 'description' => 'Information on alternative, holistic, and complementary therapies and treatments.'],
              ['name' => 'Healthcare Industry and Services', 'description' => 'News about the healthcare sector, hospital management, healthcare services, and industry trends.'],
              ['name' => 'Global Health Issues', 'description' => 'Coverage of health issues on a global scale, including epidemics, international health initiatives, and world health statistics.'],
              ['name' => 'Environmental Health', 'description' => 'The impact of environmental factors on health, including pollution, climate change, and ecological health risks.'],
              ['name' => 'Occupational Health and Safety', 'description' => 'Health and safety in the workplace, occupational hazards, and employee wellness programs.'],
              ['name' => 'Health Education and Awareness', 'description' => 'Efforts in health education, awareness campaigns, and promoting health literacy.'],
              ['name' => 'Telemedicine and Digital Health', 'description' => 'The evolving role of telemedicine, digital health platforms, and technology in healthcare delivery.'],
          ],
          'Science' => [
              ['name' => 'Astronomy and Space Exploration', 'description' => 'Covering topics related to astronomy, space missions, and discoveries beyond Earth.'],
              ['name' => 'Biology and Life Sciences', 'description' => 'Focus on biological research, evolutionary studies, and developments in life sciences.'],
              ['name' => 'Physics and Astrophysics', 'description' => 'Exploring the realms of physics, quantum mechanics, and astrophysical phenomena.'],
              ['name' => 'Chemistry and Materials Science', 'description' => 'News about chemical research, materials science innovations, and breakthroughs in chemistry.'],
              ['name' => 'Environmental Science and Ecology', 'description' => 'Studies and news related to environmental challenges, ecology, and the study of ecosystems.'],
              ['name' => 'Geology and Earth Sciences', 'description' => 'Topics on geology, earth sciences, and the study of Earth’s structure and processes.'],
              ['name' => 'Health and Medical Science', 'description' => 'Advancements and research in health sciences, medicine, and clinical studies.'],
              ['name' => 'Technology and Engineering', 'description' => 'The intersection of science with technology and engineering, including innovations and developments.'],
              ['name' => 'Psychology and Neuroscience', 'description' => 'Exploring the human mind, brain research, and developments in psychology and neuroscience.'],
              ['name' => 'Mathematics and Statistics', 'description' => 'Mathematical theories, discoveries, and the application of statistics in various scientific fields.'],
              ['name' => 'Social Sciences', 'description' => 'Covering areas such as sociology, anthropology, and human behavioral studies.'],
              ['name' => 'Agricultural and Food Sciences', 'description' => 'Science in the field of agriculture, food production, and nutritional studies.'],
              ['name' => 'Climate Science and Meteorology', 'description' => 'Research and news on climate change, meteorology, and atmospheric sciences.'],
              ['name' => 'Energy Sciences', 'description' => 'Studies on energy production, renewable energy sources, and sustainable energy technologies.'],
              ['name' => 'Computer Science and Artificial Intelligence', 'description' => 'Advancements in computer science, AI research, and the future of computing.'],
              ['name' => 'Oceanography and Marine Sciences', 'description' => 'Exploration and studies of ocean ecosystems, marine life, and oceanographic research.'],
              ['name' => 'Physics and Nanotechnology', 'description' => 'Developments in the field of nanotechnology, quantum computing, and applied physics.'],
              ['name' => 'Archaeology and Paleontology', 'description' => 'Discoveries and research in archaeology and paleontology, studying ancient life and human history.'],
              ['name' => 'Space Science and Cosmology', 'description' => 'In-depth look at cosmological theories, space research, and the study of the universe.'],
              ['name' => 'Science Policy and Ethics', 'description' => 'Discussion on science policy, ethical considerations in scientific research, and the role of science in society.'],
          ],
          'Environment' => [
              ['name' => 'Climate Change and Global Warming', 'description' => 'News and analysis on climate change, global warming trends, and their impacts on the planet.'],
              ['name' => 'Conservation and Biodiversity', 'description' => 'Efforts in wildlife conservation, biodiversity preservation, and endangered species protection.'],
              ['name' => 'Sustainable Living and Green Practices', 'description' => 'Focus on sustainable living, green lifestyle choices, and environmentally friendly practices.'],
              ['name' => 'Environmental Policy and Regulation', 'description' => 'Coverage of environmental policies, regulatory changes, and governmental initiatives for environmental protection.'],
              ['name' => 'Pollution and Waste Management', 'description' => 'Issues related to pollution control, waste management, recycling, and cleanup efforts.'],
              ['name' => 'Renewable Energy and Resources', 'description' => 'Advancements in renewable energy, sustainable resource use, and alternative energy sources.'],
              ['name' => 'Water Resources and Management', 'description' => 'Concerns and studies about water conservation, management, and issues affecting water bodies.'],
              ['name' => 'Eco-Friendly Technologies', 'description' => 'Innovations and developments in eco-friendly technologies and sustainable solutions.'],
              ['name' => 'Environmental Activism and Advocacy', 'description' => 'News about environmental activism, advocacy groups, and campaigns for ecological causes.'],
              ['name' => 'Urban Planning and Green Cities', 'description' => 'Efforts in creating sustainable urban environments, green city planning, and eco-friendly infrastructure.'],
              ['name' => 'Ocean and Marine Conservation', 'description' => 'Protection of marine ecosystems, ocean conservation initiatives, and threats to ocean health.'],
              ['name' => 'Deforestation and Land Use', 'description' => 'Issues surrounding deforestation, land degradation, and sustainable land use practices.'],
              ['name' => 'Air Quality and Atmospheric Science', 'description' => 'Studies and news on air quality, atmospheric conditions, and impacts on human health and the environment.'],
              ['name' => 'Agriculture and Environmental Impact', 'description' => 'Environmental impacts of agricultural practices, sustainable farming, and agroecology.'],
              ['name' => 'Natural Disasters and Climate Resilience', 'description' => 'Coverage of natural disasters, disaster preparedness, and building climate resilience.'],
              ['name' => 'Wildlife and Habitat Protection', 'description' => 'Efforts to protect wildlife habitats, preserve natural areas, and maintain ecosystem health.'],
              ['name' => 'Eco-Tourism and Ethical Travel', 'description' => 'Developments in eco-tourism, ethical travel choices, and their environmental impacts.'],
              ['name' => 'Energy Efficiency and Conservation', 'description' => 'Promotion of energy efficiency, conservation practices, and reducing carbon footprints.'],
              ['name' => 'Environmental Education and Awareness', 'description' => 'Efforts in environmental education, public awareness campaigns, and fostering ecological literacy.'],
              ['name' => 'Environmental Health and Safety', 'description' => 'Connections between environmental factors and human health, including safety guidelines and risks.'],
          ],
          'Education' => [
              ['name' => 'Educational Policy and Administration', 'description' => 'Covering developments in educational policies, administration, and reform at local, national, and international levels.'],
              ['name' => 'Higher Education', 'description' => 'News and issues related to universities, colleges, and higher education institutions, including research, funding, and academic trends.'],
              ['name' => 'Primary and Secondary Education', 'description' => 'Focus on elementary and secondary schools, teaching methods, curriculum developments, and school activities.'],
              ['name' => 'Early Childhood Education', 'description' => 'Advancements and discussions in early childhood education, preschools, and developmental learning in the early years.'],
              ['name' => 'Adult Education and Lifelong Learning', 'description' => 'Coverage of adult education programs, continuing education, and lifelong learning opportunities.'],
              ['name' => 'Educational Technology and E-Learning', 'description' => 'Exploring the role of technology in education, e-learning platforms, and digital learning tools.'],
              ['name' => 'Special Education', 'description' => 'News on special education, inclusive education practices, and resources for students with special needs.'],
              ['name' => 'Teacher Training and Professional Development', 'description' => 'Developments in teacher education, training programs, and professional development for educators.'],
              ['name' => 'International Education and Exchange', 'description' => 'Information about international education programs, student exchange opportunities, and global educational collaborations.'],
              ['name' => 'Vocational and Technical Education', 'description' => 'Focus on vocational training, technical schools, and career-oriented education.'],
              ['name' => 'Educational Research and Innovations', 'description' => 'Latest findings in educational research, innovative teaching methods, and educational experiments.'],
              ['name' => 'Student Life and Activities', 'description' => 'Insights into student life, extracurricular activities, student organizations, and campus events.'],
              ['name' => 'Education Funding and Scholarships', 'description' => 'Information on education funding, scholarships, grants, and financial aid for students.'],
              ['name' => 'Literacy and Language Education', 'description' => 'Efforts in promoting literacy, language teaching, and bilingual education.'],
              ['name' => 'Education for Sustainable Development', 'description' => 'Educational approaches and programs aimed at promoting sustainable development and environmental awareness.'],
              ['name' => 'Educational Equity and Diversity', 'description' => 'Issues related to educational equity, diversity in education, and access to learning opportunities.'],
              ['name' => 'School Safety and Policies', 'description' => 'Discussions on school safety, bullying, educational policies, and the well-being of students.'],
              ['name' => 'Parental Involvement and Education', 'description' => 'The role of parental involvement in education, parent-teacher interactions, and family educational practices.'],
              ['name' => 'Education Law and Ethics', 'description' => 'Legal aspects of education, ethical considerations, and education-related legal cases.'],
              ['name' => 'Cultural and Arts Education', 'description' => 'Promotion of cultural and arts education, including music, arts, and cultural studies in educational curriculums.'],
          ],
          'Sports' => [
              ['name' => 'Team Sports', 'description' => 'News and updates on team sports like football, basketball, soccer, hockey, and baseball.'],
              ['name' => 'Individual Sports', 'description' => 'Coverage of individual sports such as tennis, golf, athletics, swimming, and gymnastics.'],
              ['name' => 'Extreme and Adventure Sports', 'description' => 'Adventurous and extreme sports like rock climbing, surfing, skateboarding, and mountain biking.'],
              ['name' => 'Motor and Auto Racing', 'description' => 'All about motor sports, including Formula 1, NASCAR, motocross, and rally racing.'],
              ['name' => 'Water Sports', 'description' => 'Focus on water-related sports activities, such as rowing, sailing, water polo, and diving.'],
              ['name' => 'Winter Sports', 'description' => 'News on winter sports, including skiing, ice skating, snowboarding, and ice hockey.'],
              ['name' => 'Combat Sports and Martial Arts', 'description' => 'Coverage of combat sports and martial arts, including boxing, wrestling, judo, and MMA.'],
              ['name' => 'E-Sports and Digital Gaming', 'description' => 'The world of competitive video gaming, e-sports tournaments, and gaming leagues.'],
              ['name' => 'Fitness and Bodybuilding', 'description' => 'News on fitness trends, bodybuilding competitions, workout regimes, and health-related sports activities.'],
              ['name' => 'Olympic and International Sports', 'description' => 'Updates on Olympic sports, international competitions, and global sports events.'],
              ['name' => 'Youth and School Sports', 'description' => 'Sports activities, competitions, and news related to schools, colleges, and youth sports leagues.'],
              ['name' => 'Recreational Sports', 'description' => 'Informal and recreational sports activities, local sports clubs, and community sports events.'],
              ['name' => 'Sports Medicine and Health', 'description' => 'Information on sports injuries, rehabilitation, sports medicine, and athlete health.'],
              ['name' => 'Sports Industry and Marketing', 'description' => 'Business side of sports, including sports marketing, sponsorships, sports merchandise, and industry trends.'],
              ['name' => 'Sports Training and Coaching', 'description' => 'Techniques, coaching strategies, and training tips for various sports.'],
              ['name' => 'Sports Psychology', 'description' => 'Mental aspects of sports performance, athlete psychology, and mental training for sports.'],
              ['name' => 'Women in Sports', 'description' => 'Highlighting women\'s sports, female athletes, and gender issues in the sports world.'],
              ['name' => 'Sports Governance and Policy', 'description' => 'Policies, governance, and regulatory aspects of sporting bodies and organizations.'],
              ['name' => 'Sports History and Records', 'description' => 'Historical aspects of sports, record achievements, and notable moments in sports history.'],
              ['name' => 'Sports Journalism and Media', 'description' => 'The role of media in sports, sports journalism, and coverage of sports in the media.'],
          ],
          'Entertainment' => [
              ['name' => 'Movies and Film Industry', 'description' => 'Latest news, releases, and industry trends in the world of cinema and filmmaking.'],
              ['name' => 'Television Shows and Streaming Services', 'description' => 'Updates on TV shows, streaming content, series reviews, and digital platforms.'],
              ['name' => 'Music Industry and Concerts', 'description' => 'News about music releases, concerts, artist profiles, and music industry developments.'],
              ['name' => 'Celebrity News and Gossip', 'description' => 'Gossip, news, and updates about celebrities and high-profile personalities in entertainment.'],
              ['name' => 'Comedy and Stand-Up', 'description' => 'Insights into the world of comedy, including stand-up shows, comedians, and comedy festivals.'],
              ['name' => 'Gaming and Interactive Entertainment', 'description' => 'Coverage of video games, gaming industry trends, e-sports, and digital gaming events.'],
              ['name' => 'Fashion Trends and Events', 'description' => 'Latest trends in fashion, style, fashion shows, and developments in the fashion industry.'],
              ['name' => 'Awards and Entertainment Events', 'description' => 'Updates on entertainment awards, ceremonies, and major industry events.'],
              ['name' => 'Digital Media and Online Entertainment', 'description' => 'The evolving landscape of digital content, online media, and streaming trends.'],
              ['name' => 'Podcasts and Radio Entertainment', 'description' => 'The latest in podcasting, radio shows, and audio entertainment.'],
          ],
          'Arts and Culture' => [
              ['name' => 'Visual Arts and Exhibitions', 'description' => 'Coverage of painting, sculpture, photography, galleries, and art exhibitions.'],
              ['name' => 'Performing Arts and Theater', 'description' => 'News on theater, dance, opera, and live performance arts.'],
              ['name' => 'Literature and Books', 'description' => 'Focus on literary works, book releases, author news, and literary festivals.'],
              ['name' => 'Cultural Heritage and History', 'description' => 'Exploring cultural heritage, historical preservation, museums, and archaeology.'],
              ['name' => 'Fine Arts and Craftsmanship', 'description' => 'Spotlight on fine arts, crafts, artisanal works, and traditional artistic practices.'],
              ['name' => 'Architecture and Design', 'description' => 'Latest in architectural design, urban planning, and innovative structures.'],
              ['name' => 'Art Festivals and Cultural Events', 'description' => 'Information about art festivals, cultural celebrations, and community arts events.'],
              ['name' => 'Photography and Digital Art', 'description' => 'Insights into the world of photography, digital arts, and multimedia creations.'],
              ['name' => 'Culinary Arts and Gastronomy', 'description' => 'Exploring culinary arts, gastronomy, food culture, and culinary events.'],
              ['name' => 'World Cultures and Global Art Forms', 'description' => 'Diverse cultural expressions, global art forms, and cross-cultural artistic influences.'],
          ],
          'Lifestyle' => [
              ['name' => 'Health and Wellness', 'description' => 'Topics related to personal health, wellness trends, mental and physical well-being.'],
              ['name' => 'Fitness and Exercise', 'description' => 'Coverage of fitness trends, exercise routines, sports wellness, and active living.'],
              ['name' => 'Food and Nutrition', 'description' => 'Culinary trends, nutrition advice, recipes, and food culture.'],
              ['name' => 'Fashion and Beauty', 'description' => 'Latest trends in fashion, beauty tips, cosmetic advancements, and style guidance.'],
              ['name' => 'Travel and Leisure', 'description' => 'Travel guides, vacation ideas, leisure activities, and exploration of new destinations.'],
              ['name' => 'Home and Garden', 'description' => 'Advice and trends on home decoration, gardening, and domestic lifestyle.'],
              ['name' => 'Relationships and Family', 'description' => 'Insights into relationships, family dynamics, parenting, and personal development.'],
              ['name' => 'Personal Finance', 'description' => 'Financial advice, budgeting tips, money-saving strategies, and investment insights.'],
              ['name' => 'Self-Improvement and Motivation', 'description' => 'Tips on personal growth, self-improvement techniques, and motivational strategies.'],
              ['name' => 'Sustainable and Eco-Friendly Living', 'description' => 'Focus on sustainable practices, eco-friendly lifestyle choices, and green living.'],
              ['name' => 'Arts and DIY Crafts', 'description' => 'Do-it-yourself projects, arts and crafts, and creative hobbies.'],
              ['name' => 'Culture and Society', 'description' => 'Exploring cultural trends, societal behaviors, and community events.'],
              ['name' => 'Mindfulness and Spirituality', 'description' => 'Approaches to mindfulness, spiritual growth, and holistic living.'],
              ['name' => 'Pet Care and Animal Welfare', 'description' => 'Guidance on pet care, animal wellness, and issues related to animal welfare.'],
              ['name' => 'Technology and Gadgets', 'description' => 'Consumer technology trends, gadget reviews, and the impact of tech in daily life.'],
              ['name' => 'Automotive and Motor Vehicles', 'description' => 'Automotive trends, vehicle maintenance tips, and the world of motor vehicles.'],
              ['name' => 'Hobbies and Interests', 'description' => 'Exploration of various hobbies, interests, and recreational activities.'],
              ['name' => 'Luxury and High-End Lifestyle', 'description' => 'The world of luxury living, high-end products, and exclusive lifestyle experiences.'],
              ['name' => 'Event Planning and Celebrations', 'description' => 'Ideas and tips for event planning, celebrations, and hosting gatherings.'],
              ['name' => 'Cultural Trends and Social Movements', 'description' => 'Emerging cultural trends, social movements, and shifts in societal norms.'],
          ],
          'Opinion' => [
              ['name' => 'Editorials', 'description' => 'Authoritative opinions and viewpoints on current events and topical issues from the editorial board.'],
              ['name' => 'Commentary and Analysis', 'description' => 'In-depth analysis and commentary on political, social, and cultural issues.'],
              ['name' => 'Guest Columns', 'description' => 'Opinions and perspectives contributed by guest writers, experts, and commentators.'],
              ['name' => 'Letters to the Editor', 'description' => 'Reader-submitted opinions, reactions, and viewpoints on recent news and articles.'],
              ['name' => 'Op-Eds', 'description' => 'Opinion pieces by columnists, writers, and thinkers on a variety of subjects.'],
              ['name' => 'Social Commentary', 'description' => 'Discussions and viewpoints on social trends, societal issues, and public discourse.'],
              ['name' => 'Political Opinions', 'description' => 'Personal and subjective views on political matters, policies, and political figures.'],
              ['name' => 'Economic Perspectives', 'description' => 'Opinions and thoughts on economic policies, market trends, and financial issues.'],
              ['name' => 'Cultural Critique', 'description' => 'Critical views and commentary on cultural phenomena, arts, and entertainment.'],
              ['name' => 'Global Views', 'description' => 'International perspectives on global events, foreign policy, and cross-border issues.'],
              ['name' => 'Ethical and Moral Considerations', 'description' => 'Exploration of ethical dilemmas, moral questions, and philosophical debates.'],
              ['name' => 'Environmental Opinions', 'description' => 'Viewpoints on environmental issues, climate change, and sustainability.'],
              ['name' => 'Technology and Innovation Insights', 'description' => 'Opinions on technological advancements, digital trends, and the impact of innovation.'],
              ['name' => 'Health and Wellness Perspectives', 'description' => 'Views on health policies, medical developments, and lifestyle choices.'],
              ['name' => 'Education and Academia Opinions', 'description' => 'Thoughts and viewpoints on educational trends, policies, and academic matters.'],
              ['name' => 'Sports Commentary', 'description' => 'Personal opinions and analyses on sports events, teams, and athletic performance.'],
              ['name' => 'Business and Corporate Opinions', 'description' => 'Perspectives on business practices, corporate governance, and industry trends.'],
              ['name' => 'Personal Essays and Narratives', 'description' => 'First-person essays and narrative pieces reflecting individual experiences and viewpoints.'],
              ['name' => 'Historical Perspectives', 'description' => 'Opinions and reflections on historical events and their impact on the present.'],
              ['name' => 'Community and Local Voices', 'description' => 'Local viewpoints and opinions on community issues, events, and developments.'],
          ],
          'Crime and Justice' => [
              ['name' => 'Criminal Cases and Trials', 'description' => 'In-depth coverage of significant criminal cases, trials, and court proceedings.'],
              ['name' => 'Law Enforcement and Policing', 'description' => 'News and analysis related to law enforcement agencies, policing strategies, and police-community relations.'],
              ['name' => 'Legal Analysis and Opinion', 'description' => 'Expert opinions and analysis on legal issues, judicial decisions, and legislative changes.'],
              ['name' => 'Cybercrime and Online Safety', 'description' => 'Issues related to cybercrime, online fraud, digital security, and internet law.'],
              ['name' => 'White-Collar Crime and Fraud', 'description' => 'Coverage of white-collar crimes, financial fraud, embezzlement, and corruption.'],
              ['name' => 'Juvenile Justice', 'description' => 'Topics concerning juvenile crime, youth justice system, and rehabilitation programs for young offenders.'],
              ['name' => 'Human Rights and Civil Liberties', 'description' => 'Discussion of human rights issues, civil liberties, and legal protections.'],
              ['name' => 'Prison System and Correctional Facilities', 'description' => 'News about the prison system, correctional policies, inmate rehabilitation, and life inside correctional facilities.'],
              ['name' => 'Victim\'s Rights and Advocacy', 'description' => 'Focus on victim\'s rights, support for crime victims, and advocacy groups.'],
              ['name' => 'International Law and War Crimes', 'description' => 'Insights into international law, war crimes, tribunals, and global justice issues.'],
              ['name' => 'Drug Enforcement and Narcotics', 'description' => 'Information on drug-related crimes, narcotics enforcement, and substance abuse policies.'],
              ['name' => 'Forensic Science and Investigations', 'description' => 'Advancements in forensic science, criminal investigations, and detective work.'],
              ['name' => 'Organized Crime and Gangs', 'description' => 'Reports on organized crime, gang activities, and efforts to combat organized criminal networks.'],
              ['name' => 'Terrorism and Counterterrorism', 'description' => 'Coverage of terrorism, counterterrorism measures, and national security issues.'],
              ['name' => 'Domestic Violence and Abuse', 'description' => 'Addressing issues of domestic violence, abuse, and protective measures for victims.'],
              ['name' => 'Traffic Law and Road Safety', 'description' => 'Legal aspects of traffic regulation, road safety initiatives, and vehicular crimes.'],
              ['name' => 'Environmental Crimes and Regulations', 'description' => 'Crimes against the environment, wildlife poaching, and environmental regulations.'],
              ['name' => 'Family Law and Custody', 'description' => 'Topics related to family law, custody battles, and domestic legal disputes.'],
              ['name' => 'Immigration Law and Policy', 'description' => 'Issues surrounding immigration law, asylum cases, and border enforcement policies.'],
              ['name' => 'Public Interest Law and Advocacy', 'description' => 'Legal efforts in the public interest, advocacy for legal reforms, and access to justice.'],
          ],
          'Human Interest' => [
              ['name' => 'Personal Stories and Experiences', 'description' => 'In-depth narratives and personal accounts highlighting individual experiences and journeys.'],
              ['name' => 'Community Heroes and Inspirational Lives', 'description' => 'Stories of remarkable individuals, community heroes, and people making a positive impact.'],
              ['name' => 'Cultural Traditions and Practices', 'description' => 'Exploring diverse cultural traditions, practices, and heritages from around the world.'],
              ['name' => 'Social Issues and Awareness', 'description' => 'Highlighting important social issues, awareness campaigns, and movements for change.'],
              ['name' => 'Lifestyle and Daily Living', 'description' => 'Insights into various lifestyles, daily living experiences, and societal norms.'],
              ['name' => 'Relationships and Family Dynamics', 'description' => 'Exploring the dynamics of personal relationships, family life, and interpersonal connections.'],
              ['name' => 'Adventure and Exploration', 'description' => 'Captivating stories of adventure, exploration, travel experiences, and discoveries.'],
              ['name' => 'Overcoming Challenges and Resilience', 'description' => 'Inspirational accounts of overcoming obstacles, resilience, and triumph against adversity.'],
              ['name' => 'Arts, Creativity, and Innovation', 'description' => 'Showcasing artistic talents, creative endeavors, and innovative ideas.'],
              ['name' => 'Historical Accounts and Nostalgia', 'description' => 'Revisiting historical events, personal histories, and nostalgic reminiscences.'],
              ['name' => 'Animal Stories and Wildlife', 'description' => 'Heartwarming and intriguing stories about animals, pets, and wildlife encounters.'],
              ['name' => 'Health, Wellness, and Recovery', 'description' => 'Personal health journeys, wellness transformations, and stories of recovery.'],
              ['name' => 'Achievements and Success Stories', 'description' => 'Celebrating personal achievements, success stories, and milestones.'],
              ['name' => 'Hobbies and Passions', 'description' => 'Exploring individual hobbies, passions, and recreational pursuits.'],
              ['name' => 'Youth and Education', 'description' => 'Stories focusing on youth, educational experiences, and growth during formative years.'],
              ['name' => 'Senior Experiences and Wisdom', 'description' => 'Insights and life lessons from the senior population and their experiences.'],
              ['name' => 'Charity, Volunteering, and Philanthropy', 'description' => 'Highlighting acts of charity, volunteer efforts, and philanthropic initiatives.'],
              ['name' => 'Workplace and Professional Experiences', 'description' => 'Anecdotes and stories from various professional fields and workplace environments.'],
              ['name' => 'Travel Tales and World Experiences', 'description' => 'Entertaining and enlightening travel tales and experiences from around the globe.'],
              ['name' => 'Environmental Awareness and Conservation Efforts', 'description' => 'Personal and community stories related to environmental conservation and awareness.'],
          ],
          'Weather' => [
              ['name' => 'Local Weather Reports', 'description' => 'Daily updates and forecasts on local weather conditions, temperature changes, and regional weather patterns.'],
              ['name' => 'Severe Weather Alerts', 'description' => 'Timely alerts and coverage of severe weather events like storms, hurricanes, blizzards, and floods.'],
              ['name' => 'Climate Change and Meteorology', 'description' => 'Insights into climate change trends, meteorological studies, and long-term climate patterns.'],
              ['name' => 'Weather Science and Education', 'description' => 'Educational content on weather phenomena, meteorological science, and understanding weather patterns.'],
              ['name' => 'Extreme Weather Events', 'description' => 'Reporting on extreme weather occurrences such as heatwaves, cold snaps, and unusual weather conditions.'],
              ['name' => 'Weather Impact on Agriculture', 'description' => 'How weather conditions affect agriculture, crop production, and farming practices.'],
              ['name' => 'Weather-Related Safety and Preparedness', 'description' => 'Guidance on safety measures, emergency preparedness, and protective actions during adverse weather.'],
              ['name' => 'Historical Weather Events', 'description' => 'Looking back at significant historical weather events and their impacts.'],
              ['name' => 'Global Weather Patterns', 'description' => 'Analysis of global weather phenomena, international climate issues, and large-scale weather patterns.'],
              ['name' => 'Weather Photography and Videography', 'description' => 'Showcasing weather photography, storm chasing experiences, and visual documentation of weather events.'],
              ['name' => 'Environmental and Ecological Effects', 'description' => 'Exploring the effects of weather on the environment, ecosystems, and biodiversity.'],
              ['name' => 'Weather in Popular Culture', 'description' => 'Weather as it appears in literature, film, art, and popular culture.'],
              ['name' => 'Weather Forecasting Technology', 'description' => 'Advancements in weather forecasting technology, tools, and prediction methods.'],
              ['name' => 'Astronomical Events and Weather', 'description' => 'Coverage of astronomical events and their influence on Earth’s weather.'],
              ['name' => 'Ocean and Marine Weather', 'description' => 'Weather conditions affecting oceans, marine life, and maritime activities.'],
              ['name' => 'Air Quality and Pollution', 'description' => 'Information on air quality, pollution levels, and their health impacts related to weather conditions.'],
              ['name' => 'Urban Weather Phenomena', 'description' => 'Unique weather phenomena and microclimates in urban settings.'],
              ['name' => 'Weather and Travel', 'description' => 'Impacts of weather on travel plans, advisories, and travel safety tips.'],
              ['name' => 'Weather in Sports and Recreation', 'description' => 'How weather affects sports events, outdoor activities, and recreational planning.'],
              ['name' => 'Seasonal Weather Changes', 'description' => 'Coverage of seasonal weather transitions, patterns, and related lifestyle adjustments.'],
          ],
          'Transportation' => [
              ['name' => 'Public Transportation Systems', 'description' => 'News and updates on public transportation, including buses, trains, subways, and trams.'],
              ['name' => 'Automotive and Private Vehicles', 'description' => 'Coverage of automotive industry news, car models, vehicle technology, and private vehicle use.'],
              ['name' => 'Air Travel and Airlines', 'description' => 'Updates and news related to air travel, airlines, airports, and aviation industry trends.'],
              ['name' => 'Maritime and Shipping', 'description' => 'News about maritime transport, shipping industries, ports, and naval technology.'],
              ['name' => 'Cycling and Urban Mobility', 'description' => 'Focus on cycling, bike-sharing systems, and sustainable urban mobility solutions.'],
              ['name' => 'Freight and Logistics', 'description' => 'Information on freight transportation, logistics, supply chain management, and cargo services.'],
              ['name' => 'Rail Transport and Railroads', 'description' => 'News on rail transport, railway infrastructure, train services, and railroad industry developments.'],
              ['name' => 'Transportation Policy and Regulation', 'description' => 'Coverage of transportation policies, regulations, and governmental initiatives.'],
              ['name' => 'Infrastructure and Road Networks', 'description' => 'Updates on transportation infrastructure, road networks, bridges, and tunnel construction.'],
              ['name' => 'Electric and Alternative Fuel Vehicles', 'description' => 'Advancements in electric vehicles, alternative fuels, and sustainable transportation technologies.'],
              ['name' => 'Traffic and Road Safety', 'description' => 'Information on traffic conditions, road safety initiatives, and driving tips.'],
              ['name' => 'Transportation Innovation and Future Trends', 'description' => 'Emerging trends and innovative developments in transportation, including autonomous vehicles and smart transportation systems.'],
              ['name' => 'Space Travel and Exploration', 'description' => 'News on space travel, spacecraft, and developments in space exploration.'],
              ['name' => 'Pedestrian Movement and Walkability', 'description' => 'Focus on pedestrian rights, walkability in cities, and urban design for pedestrian movement.'],
              ['name' => 'Transportation Accessibility and Equity', 'description' => 'Issues related to transportation accessibility, inclusivity, and equitable transit solutions.'],
              ['name' => 'Environmental Impact of Transportation', 'description' => 'Exploring the environmental implications of various transportation modes and efforts to reduce transport-related emissions.'],
              ['name' => 'Ridesharing and Taxis', 'description' => 'The evolving landscape of ridesharing services, taxis, and app-based transportation options.'],
              ['name' => 'Emergency Transportation Services', 'description' => 'Role and importance of emergency transportation services in public safety and healthcare.'],
              ['name' => 'Urban Planning and Transportation', 'description' => 'The intersection of urban planning and transportation design in creating efficient and livable cities.'],
              ['name' => 'Travel Planning and Commuting', 'description' => 'Advice and tips on travel planning, commuting strategies, and making transportation choices.'],
          ],
      ];

      $batchSize = 500; // Define a suitable batch size
      $batchData = []; // Array to hold batch data

      foreach ($subCategoryGroups as $categoryName => $subCategories) {
        $categoryId = $this->getCategoryIdByName($categoryName);
        if ($categoryId) {
          $this->addCategoryId($subCategories, $categoryId);
          $this->addTimestamps($subCategories);

          foreach ($subCategories as $subCategory) {
            $batchData[] = $subCategory;

            if (count($batchData) >= $batchSize) {
              DB::table('news_category_subs')->insert($batchData);
              $batchData = []; // Reset the batch data
            }
          }
        }
      }

      // Insert any remaining records
      if (!empty($batchData)) {
        DB::table('news_category_subs')->insert($batchData);
      }
    }

  private function addTimestamps(array &$items)
  {
    $timestamp = now();
    foreach ($items as &$item) {
      $item['created_at'] = $timestamp;
      $item['updated_at'] = $timestamp;
    }
  }

  private function getCategoryIdByName($categoryName)
  {
    $category = DB::table('news_categories')->where('name', $categoryName)->first();
    return $category ? $category->id : null;
  }

  private function addCategoryId(&$subCategoryArray, $categoryId)
  {
    foreach ($subCategoryArray as &$subCategory) {
      $subCategory['news_categories_id'] = $categoryId;
    }
  }
}
