<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
      // Make sure to adjust 'teams' and 'team_leader' to match your actual table and column names
      Schema::table('teams', function (Blueprint $table) {
        // First, drop the existing foreign key
        // The foreign key constraint name might differ; you can find it using `php artisan migrate:status`
        // or by looking at your database schema. It's often autogenerated in the format `table_column_foreign`.
        $table->dropForeign(['team_leader']);

        // Then, re-add the foreign key with the desired onDelete behavior
        $table->foreign('team_leader')
            ->references('id')->on('creators')
            ->onDelete('SET NULL');
      });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
      Schema::table('teams', function (Blueprint $table) {
        $table->dropForeign(['team_leader']);

        // Re-add the original foreign key without onDelete SET NULL
        $table->foreign('team_leader')
            ->references('id')->on('creators');
        // If you had a specific onDelete behavior before, specify it here
      });
    }
};
